# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.address_geofence import AddressGeofence
from openapi_server import util

from openapi_server.models.address_geofence import AddressGeofence  # noqa: E501

class InlineObject1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, contact_ids=None, formatted_address=None, geofence=None, name=None, notes=None, tag_ids=None):  # noqa: E501
        """InlineObject1 - a model defined in OpenAPI

        :param contact_ids: The contact_ids of this InlineObject1.  # noqa: E501
        :type contact_ids: List[int]
        :param formatted_address: The formatted_address of this InlineObject1.  # noqa: E501
        :type formatted_address: str
        :param geofence: The geofence of this InlineObject1.  # noqa: E501
        :type geofence: AddressGeofence
        :param name: The name of this InlineObject1.  # noqa: E501
        :type name: str
        :param notes: The notes of this InlineObject1.  # noqa: E501
        :type notes: str
        :param tag_ids: The tag_ids of this InlineObject1.  # noqa: E501
        :type tag_ids: List[int]
        """
        self.openapi_types = {
            'contact_ids': List[int],
            'formatted_address': str,
            'geofence': AddressGeofence,
            'name': str,
            'notes': str,
            'tag_ids': List[int]
        }

        self.attribute_map = {
            'contact_ids': 'contactIds',
            'formatted_address': 'formattedAddress',
            'geofence': 'geofence',
            'name': 'name',
            'notes': 'notes',
            'tag_ids': 'tagIds'
        }

        self._contact_ids = contact_ids
        self._formatted_address = formatted_address
        self._geofence = geofence
        self._name = name
        self._notes = notes
        self._tag_ids = tag_ids

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_1 of this InlineObject1.  # noqa: E501
        :rtype: InlineObject1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contact_ids(self):
        """Gets the contact_ids of this InlineObject1.

        A list of IDs for contact book entries.  # noqa: E501

        :return: The contact_ids of this InlineObject1.
        :rtype: List[int]
        """
        return self._contact_ids

    @contact_ids.setter
    def contact_ids(self, contact_ids):
        """Sets the contact_ids of this InlineObject1.

        A list of IDs for contact book entries.  # noqa: E501

        :param contact_ids: The contact_ids of this InlineObject1.
        :type contact_ids: List[int]
        """

        self._contact_ids = contact_ids

    @property
    def formatted_address(self):
        """Gets the formatted_address of this InlineObject1.

        The full address associated with this address/geofence, as it might be recognized by maps.google.com  # noqa: E501

        :return: The formatted_address of this InlineObject1.
        :rtype: str
        """
        return self._formatted_address

    @formatted_address.setter
    def formatted_address(self, formatted_address):
        """Sets the formatted_address of this InlineObject1.

        The full address associated with this address/geofence, as it might be recognized by maps.google.com  # noqa: E501

        :param formatted_address: The formatted_address of this InlineObject1.
        :type formatted_address: str
        """

        self._formatted_address = formatted_address

    @property
    def geofence(self):
        """Gets the geofence of this InlineObject1.


        :return: The geofence of this InlineObject1.
        :rtype: AddressGeofence
        """
        return self._geofence

    @geofence.setter
    def geofence(self, geofence):
        """Sets the geofence of this InlineObject1.


        :param geofence: The geofence of this InlineObject1.
        :type geofence: AddressGeofence
        """

        self._geofence = geofence

    @property
    def name(self):
        """Gets the name of this InlineObject1.

        The name of this address/geofence  # noqa: E501

        :return: The name of this InlineObject1.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineObject1.

        The name of this address/geofence  # noqa: E501

        :param name: The name of this InlineObject1.
        :type name: str
        """

        self._name = name

    @property
    def notes(self):
        """Gets the notes of this InlineObject1.

        Notes associated with an address.  # noqa: E501

        :return: The notes of this InlineObject1.
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this InlineObject1.

        Notes associated with an address.  # noqa: E501

        :param notes: The notes of this InlineObject1.
        :type notes: str
        """

        self._notes = notes

    @property
    def tag_ids(self):
        """Gets the tag_ids of this InlineObject1.

        A list of tag IDs.  # noqa: E501

        :return: The tag_ids of this InlineObject1.
        :rtype: List[int]
        """
        return self._tag_ids

    @tag_ids.setter
    def tag_ids(self, tag_ids):
        """Sets the tag_ids of this InlineObject1.

        A list of tag IDs.  # noqa: E501

        :param tag_ids: The tag_ids of this InlineObject1.
        :type tag_ids: List[int]
        """

        self._tag_ids = tag_ids
