# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.machine_history_response_vibrations import MachineHistoryResponseVibrations
from openapi_server import util

from openapi_server.models.machine_history_response_vibrations import MachineHistoryResponseVibrations  # noqa: E501

class MachineHistoryResponseMachines(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, id=None, vibrations=None):  # noqa: E501
        """MachineHistoryResponseMachines - a model defined in OpenAPI

        :param name: The name of this MachineHistoryResponseMachines.  # noqa: E501
        :type name: str
        :param id: The id of this MachineHistoryResponseMachines.  # noqa: E501
        :type id: int
        :param vibrations: The vibrations of this MachineHistoryResponseMachines.  # noqa: E501
        :type vibrations: List[MachineHistoryResponseVibrations]
        """
        self.openapi_types = {
            'name': str,
            'id': int,
            'vibrations': List[MachineHistoryResponseVibrations]
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id',
            'vibrations': 'vibrations'
        }

        self._name = name
        self._id = id
        self._vibrations = vibrations

    @classmethod
    def from_dict(cls, dikt) -> 'MachineHistoryResponseMachines':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineHistoryResponse_machines of this MachineHistoryResponseMachines.  # noqa: E501
        :rtype: MachineHistoryResponseMachines
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this MachineHistoryResponseMachines.

        Machine name  # noqa: E501

        :return: The name of this MachineHistoryResponseMachines.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MachineHistoryResponseMachines.

        Machine name  # noqa: E501

        :param name: The name of this MachineHistoryResponseMachines.
        :type name: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this MachineHistoryResponseMachines.

        Machine ID  # noqa: E501

        :return: The id of this MachineHistoryResponseMachines.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MachineHistoryResponseMachines.

        Machine ID  # noqa: E501

        :param id: The id of this MachineHistoryResponseMachines.
        :type id: int
        """

        self._id = id

    @property
    def vibrations(self):
        """Gets the vibrations of this MachineHistoryResponseMachines.

        List of vibration datapoints, with timestamp and vibration measurement for x/y/z axis in mm/s  # noqa: E501

        :return: The vibrations of this MachineHistoryResponseMachines.
        :rtype: List[MachineHistoryResponseVibrations]
        """
        return self._vibrations

    @vibrations.setter
    def vibrations(self, vibrations):
        """Sets the vibrations of this MachineHistoryResponseMachines.

        List of vibration datapoints, with timestamp and vibration measurement for x/y/z axis in mm/s  # noqa: E501

        :param vibrations: The vibrations of this MachineHistoryResponseMachines.
        :type vibrations: List[MachineHistoryResponseVibrations]
        """

        self._vibrations = vibrations
