# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class VehicleMaintenancePassengerDiagnosticTroubleCodes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, dtc_short_code=None, dtc_id=None, dtc_description=None):  # noqa: E501
        """VehicleMaintenancePassengerDiagnosticTroubleCodes - a model defined in OpenAPI

        :param dtc_short_code: The dtc_short_code of this VehicleMaintenancePassengerDiagnosticTroubleCodes.  # noqa: E501
        :type dtc_short_code: str
        :param dtc_id: The dtc_id of this VehicleMaintenancePassengerDiagnosticTroubleCodes.  # noqa: E501
        :type dtc_id: int
        :param dtc_description: The dtc_description of this VehicleMaintenancePassengerDiagnosticTroubleCodes.  # noqa: E501
        :type dtc_description: str
        """
        self.openapi_types = {
            'dtc_short_code': str,
            'dtc_id': int,
            'dtc_description': str
        }

        self.attribute_map = {
            'dtc_short_code': 'dtcShortCode',
            'dtc_id': 'dtcId',
            'dtc_description': 'dtcDescription'
        }

        self._dtc_short_code = dtc_short_code
        self._dtc_id = dtc_id
        self._dtc_description = dtc_description

    @classmethod
    def from_dict(cls, dikt) -> 'VehicleMaintenancePassengerDiagnosticTroubleCodes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VehicleMaintenance_passenger_diagnosticTroubleCodes of this VehicleMaintenancePassengerDiagnosticTroubleCodes.  # noqa: E501
        :rtype: VehicleMaintenancePassengerDiagnosticTroubleCodes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dtc_short_code(self):
        """Gets the dtc_short_code of this VehicleMaintenancePassengerDiagnosticTroubleCodes.


        :return: The dtc_short_code of this VehicleMaintenancePassengerDiagnosticTroubleCodes.
        :rtype: str
        """
        return self._dtc_short_code

    @dtc_short_code.setter
    def dtc_short_code(self, dtc_short_code):
        """Sets the dtc_short_code of this VehicleMaintenancePassengerDiagnosticTroubleCodes.


        :param dtc_short_code: The dtc_short_code of this VehicleMaintenancePassengerDiagnosticTroubleCodes.
        :type dtc_short_code: str
        """

        self._dtc_short_code = dtc_short_code

    @property
    def dtc_id(self):
        """Gets the dtc_id of this VehicleMaintenancePassengerDiagnosticTroubleCodes.


        :return: The dtc_id of this VehicleMaintenancePassengerDiagnosticTroubleCodes.
        :rtype: int
        """
        return self._dtc_id

    @dtc_id.setter
    def dtc_id(self, dtc_id):
        """Sets the dtc_id of this VehicleMaintenancePassengerDiagnosticTroubleCodes.


        :param dtc_id: The dtc_id of this VehicleMaintenancePassengerDiagnosticTroubleCodes.
        :type dtc_id: int
        """

        self._dtc_id = dtc_id

    @property
    def dtc_description(self):
        """Gets the dtc_description of this VehicleMaintenancePassengerDiagnosticTroubleCodes.


        :return: The dtc_description of this VehicleMaintenancePassengerDiagnosticTroubleCodes.
        :rtype: str
        """
        return self._dtc_description

    @dtc_description.setter
    def dtc_description(self, dtc_description):
        """Sets the dtc_description of this VehicleMaintenancePassengerDiagnosticTroubleCodes.


        :param dtc_description: The dtc_description of this VehicleMaintenancePassengerDiagnosticTroubleCodes.
        :type dtc_description: str
        """

        self._dtc_description = dtc_description
