/*
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.samsara.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class HosAuthenticationLogsParam 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4173512003005246127L;
    private long driverId;
    private long endMs;
    private long groupId;
    private long startMs;
    /** GETTER
     * Driver ID to query.
     */
    @JsonGetter("driverId")
    public long getDriverId ( ) { 
        return this.driverId;
    }
    
    /** SETTER
     * Driver ID to query.
     */
    @JsonSetter("driverId")
    public void setDriverId (long value) { 
        this.driverId = value;
    }
 
    /** GETTER
     * End of the time range, specified in milliseconds UNIX time.
     */
    @JsonGetter("endMs")
    public long getEndMs ( ) { 
        return this.endMs;
    }
    
    /** SETTER
     * End of the time range, specified in milliseconds UNIX time.
     */
    @JsonSetter("endMs")
    public void setEndMs (long value) { 
        this.endMs = value;
    }
 
    /** GETTER
     * Group ID to query.
     */
    @JsonGetter("groupId")
    public long getGroupId ( ) { 
        return this.groupId;
    }
    
    /** SETTER
     * Group ID to query.
     */
    @JsonSetter("groupId")
    public void setGroupId (long value) { 
        this.groupId = value;
    }
 
    /** GETTER
     * Beginning of the time range, specified in milliseconds UNIX time.
     */
    @JsonGetter("startMs")
    public long getStartMs ( ) { 
        return this.startMs;
    }
    
    /** SETTER
     * Beginning of the time range, specified in milliseconds UNIX time.
     */
    @JsonSetter("startMs")
    public void setStartMs (long value) { 
        this.startMs = value;
    }
 
}
