/*
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.samsara.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class HumidityResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5324308014141717429L;
    private Long groupId;
    private List<Sensor2> sensors;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("groupId")
    public Long getGroupId ( ) { 
        return this.groupId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("groupId")
    public void setGroupId (Long value) { 
        this.groupId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sensors")
    public List<Sensor2> getSensors ( ) { 
        return this.sensors;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sensors")
    public void setSensors (List<Sensor2> value) { 
        this.sensors = value;
    }
 
}
