/*
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.samsara.api.models;

import java.util.*;

public class TaggedMachineBuilder {
    //the instance to build
    private TaggedMachine taggedMachine;

    /**
     * Default constructor to initialize the instance
     */
    public TaggedMachineBuilder() {
        taggedMachine = new TaggedMachine();
    }

    /**
     * The ID of the Machine being tagged.
     */
    public TaggedMachineBuilder id(long id) {
        taggedMachine.setId(id);
        return this;
    }

    /**
     * Name of the Machine being tagged.
     */
    public TaggedMachineBuilder name(String name) {
        taggedMachine.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaggedMachine build() {
        return taggedMachine;
    }
}