{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import Samsara.Model
import Samsara.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 5) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy Address)
      propMimeEq MimeJSON (Proxy :: Proxy AddressGeofence)
      propMimeEq MimeJSON (Proxy :: Proxy AddressGeofenceCircle)
      propMimeEq MimeJSON (Proxy :: Proxy AddressGeofencePolygon)
      propMimeEq MimeJSON (Proxy :: Proxy AddressGeofencePolygonVertices)
      propMimeEq MimeJSON (Proxy :: Proxy AddressesAddresses)
      propMimeEq MimeJSON (Proxy :: Proxy AllRouteJobUpdates)
      propMimeEq MimeJSON (Proxy :: Proxy Asset)
      propMimeEq MimeJSON (Proxy :: Proxy AssetCable)
      propMimeEq MimeJSON (Proxy :: Proxy AssetCurrentLocation)
      propMimeEq MimeJSON (Proxy :: Proxy AssetCurrentLocationsResponse)
      propMimeEq MimeJSON (Proxy :: Proxy AssetReeferResponse)
      propMimeEq MimeJSON (Proxy :: Proxy AssetReeferResponseReeferStats)
      propMimeEq MimeJSON (Proxy :: Proxy AssetReeferResponseReeferStatsAlarms)
      propMimeEq MimeJSON (Proxy :: Proxy AssetReeferResponseReeferStatsAlarms1)
      propMimeEq MimeJSON (Proxy :: Proxy AssetReeferResponseReeferStatsEngineHours)
      propMimeEq MimeJSON (Proxy :: Proxy AssetReeferResponseReeferStatsFuelPercentage)
      propMimeEq MimeJSON (Proxy :: Proxy AssetReeferResponseReeferStatsPowerStatus)
      propMimeEq MimeJSON (Proxy :: Proxy AssetReeferResponseReeferStatsReturnAirTemp)
      propMimeEq MimeJSON (Proxy :: Proxy AssetReeferResponseReeferStatsSetPoint)
      propMimeEq MimeJSON (Proxy :: Proxy AuxInput)
      propMimeEq MimeJSON (Proxy :: Proxy AuxInputSeries)
      propMimeEq MimeJSON (Proxy :: Proxy CargoResponse)
      propMimeEq MimeJSON (Proxy :: Proxy CargoResponseSensors)
      propMimeEq MimeJSON (Proxy :: Proxy Contact)
      propMimeEq MimeJSON (Proxy :: Proxy CurrentDriver)
      propMimeEq MimeJSON (Proxy :: Proxy DataInputHistoryResponse)
      propMimeEq MimeJSON (Proxy :: Proxy DataInputHistoryResponsePoints)
      propMimeEq MimeJSON (Proxy :: Proxy DispatchJob)
      propMimeEq MimeJSON (Proxy :: Proxy DispatchJobCreate)
      propMimeEq MimeJSON (Proxy :: Proxy DispatchRoute)
      propMimeEq MimeJSON (Proxy :: Proxy DispatchRouteBase)
      propMimeEq MimeJSON (Proxy :: Proxy DispatchRouteCreate)
      propMimeEq MimeJSON (Proxy :: Proxy DispatchRouteHistoricalEntry)
      propMimeEq MimeJSON (Proxy :: Proxy DispatchRouteHistory)
      propMimeEq MimeJSON (Proxy :: Proxy Document)
      propMimeEq MimeJSON (Proxy :: Proxy DocumentBase)
      propMimeEq MimeJSON (Proxy :: Proxy DocumentCreate)
      propMimeEq MimeJSON (Proxy :: Proxy DocumentField)
      propMimeEq MimeJSON (Proxy :: Proxy DocumentFieldCreate)
      propMimeEq MimeJSON (Proxy :: Proxy DocumentFieldCreatePhotoValue)
      propMimeEq MimeJSON (Proxy :: Proxy DocumentFieldType)
      propMimeEq MimeJSON (Proxy :: Proxy DocumentFieldTypeNumberValueTypeMetadata)
      propMimeEq MimeJSON (Proxy :: Proxy DocumentType)
      propMimeEq MimeJSON (Proxy :: Proxy DoorResponse)
      propMimeEq MimeJSON (Proxy :: Proxy DoorResponseSensors)
      propMimeEq MimeJSON (Proxy :: Proxy Driver)
      propMimeEq MimeJSON (Proxy :: Proxy DriverBase)
      propMimeEq MimeJSON (Proxy :: Proxy DriverDailyLogResponse)
      propMimeEq MimeJSON (Proxy :: Proxy DriverDailyLogResponseDays)
      propMimeEq MimeJSON (Proxy :: Proxy DriverForCreate)
      propMimeEq MimeJSON (Proxy :: Proxy DriverSafetyScoreResponse)
      propMimeEq MimeJSON (Proxy :: Proxy DriversResponse)
      propMimeEq MimeJSON (Proxy :: Proxy DriversSummaryResponse)
      propMimeEq MimeJSON (Proxy :: Proxy DriversSummaryResponseSummaries)
      propMimeEq MimeJSON (Proxy :: Proxy DvirBase)
      propMimeEq MimeJSON (Proxy :: Proxy DvirBaseAuthorSignature)
      propMimeEq MimeJSON (Proxy :: Proxy DvirBaseMechanicOrAgentSignature)
      propMimeEq MimeJSON (Proxy :: Proxy DvirBaseNextDriverSignature)
      propMimeEq MimeJSON (Proxy :: Proxy DvirBaseTrailerDefects)
      propMimeEq MimeJSON (Proxy :: Proxy DvirBaseVehicle)
      propMimeEq MimeJSON (Proxy :: Proxy DvirListResponse)
      propMimeEq MimeJSON (Proxy :: Proxy EngineState)
      propMimeEq MimeJSON (Proxy :: Proxy FleetVehicleLocation)
      propMimeEq MimeJSON (Proxy :: Proxy FleetVehicleResponse)
      propMimeEq MimeJSON (Proxy :: Proxy FleetVehicleResponseVehicleInfo)
      propMimeEq MimeJSON (Proxy :: Proxy HosAuthenticationLogsResponse)
      propMimeEq MimeJSON (Proxy :: Proxy HosAuthenticationLogsResponseAuthenticationLogs)
      propMimeEq MimeJSON (Proxy :: Proxy HosLogsResponse)
      propMimeEq MimeJSON (Proxy :: Proxy HosLogsResponseLogs)
      propMimeEq MimeJSON (Proxy :: Proxy HosLogsSummaryResponse)
      propMimeEq MimeJSON (Proxy :: Proxy HosLogsSummaryResponseDrivers)
      propMimeEq MimeJSON (Proxy :: Proxy HumidityResponse)
      propMimeEq MimeJSON (Proxy :: Proxy HumidityResponseSensors)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject1)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject10)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject11)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject12)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject13)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject14)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject15)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject16)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject17)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject18)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject19)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject2)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject20)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject21)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject22)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject23)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject24)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject3)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject4)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject5)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject6)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject7)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject8)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject9)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse200)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2001)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2002)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2003)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2004)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2005)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2005VehicleStats)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2006)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2007)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2008)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2009)
      propMimeEq MimeJSON (Proxy :: Proxy JobStatus)
      propMimeEq MimeJSON (Proxy :: Proxy JobUpdateObject)
      propMimeEq MimeJSON (Proxy :: Proxy Machine)
      propMimeEq MimeJSON (Proxy :: Proxy MachineHistoryResponse)
      propMimeEq MimeJSON (Proxy :: Proxy MachineHistoryResponseMachines)
      propMimeEq MimeJSON (Proxy :: Proxy MachineHistoryResponseVibrations)
      propMimeEq MimeJSON (Proxy :: Proxy Pagination)
      propMimeEq MimeJSON (Proxy :: Proxy PrevJobStatus)
      propMimeEq MimeJSON (Proxy :: Proxy SafetyReportHarshEvent)
      propMimeEq MimeJSON (Proxy :: Proxy Sensor)
      propMimeEq MimeJSON (Proxy :: Proxy SensorHistoryResponse)
      propMimeEq MimeJSON (Proxy :: Proxy SensorHistoryResponseResults)
      propMimeEq MimeJSON (Proxy :: Proxy SensorsHistorySeries)
      propMimeEq MimeJSON (Proxy :: Proxy Tag)
      propMimeEq MimeJSON (Proxy :: Proxy TagCreate)
      propMimeEq MimeJSON (Proxy :: Proxy TagMetadata)
      propMimeEq MimeJSON (Proxy :: Proxy TagModify)
      propMimeEq MimeJSON (Proxy :: Proxy TagModifyAdd)
      propMimeEq MimeJSON (Proxy :: Proxy TagModifyDelete)
      propMimeEq MimeJSON (Proxy :: Proxy TagUpdate)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedAddress)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedAddressBase)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedAsset)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedAssetBase)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedDriver)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedDriverBase)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedMachine)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedMachineBase)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedSensor)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedSensorBase)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedVehicle)
      propMimeEq MimeJSON (Proxy :: Proxy TaggedVehicleBase)
      propMimeEq MimeJSON (Proxy :: Proxy TemperatureResponse)
      propMimeEq MimeJSON (Proxy :: Proxy TemperatureResponseSensors)
      propMimeEq MimeJSON (Proxy :: Proxy TripResponse)
      propMimeEq MimeJSON (Proxy :: Proxy TripResponseEndCoordinates)
      propMimeEq MimeJSON (Proxy :: Proxy TripResponseStartCoordinates)
      propMimeEq MimeJSON (Proxy :: Proxy TripResponseTrips)
      propMimeEq MimeJSON (Proxy :: Proxy User)
      propMimeEq MimeJSON (Proxy :: Proxy UserBase)
      propMimeEq MimeJSON (Proxy :: Proxy UserRole)
      propMimeEq MimeJSON (Proxy :: Proxy UserTagRole)
      propMimeEq MimeJSON (Proxy :: Proxy UserTagRoleTag)
      propMimeEq MimeJSON (Proxy :: Proxy Vehicle)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleHarshEventResponse)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleHarshEventResponseLocation)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleLocation)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleMaintenance)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleMaintenanceJ1939)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleMaintenanceJ1939CheckEngineLight)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleMaintenanceJ1939DiagnosticTroubleCodes)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleMaintenancePassenger)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleMaintenancePassengerCheckEngineLight)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleMaintenancePassengerDiagnosticTroubleCodes)
      propMimeEq MimeJSON (Proxy :: Proxy VehicleSafetyScoreResponse)
      
