//
// AssetReeferResponseReeferStatsSetPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


open class AssetReeferResponseReeferStatsSetPoint: JSONEncodable {

    /** Set point temperature in millidegree Celsius. */
    public var tempInMilliC: Int64?
    /** Timestamp in Unix milliseconds since epoch. */
    public var changedAtMs: Int64?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["tempInMilliC"] = self.tempInMilliC?.encodeToJSON()
        nillableDictionary["changedAtMs"] = self.changedAtMs?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

