//
// InlineResponse2003.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


open class InlineResponse2003: JSONEncodable {

    /** Group ID to query. */
    public var groupId: Int64?
    public var vehicles: [VehicleLocation]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["groupId"] = self.groupId?.encodeToJSON()
        nillableDictionary["vehicles"] = self.vehicles?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

