//
// InlineObject9.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


open class InlineObject9: JSONEncodable {

    /** Group ID to query. */
    public var groupId: Int64?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["groupId"] = self.groupId?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

