# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class SafetyReportHarshEvent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, harsh_event_type: str=None, timestamp_ms: int=None, vehicle_id: int=None):
        """SafetyReportHarshEvent - a model defined in OpenAPI

        :param harsh_event_type: The harsh_event_type of this SafetyReportHarshEvent.
        :param timestamp_ms: The timestamp_ms of this SafetyReportHarshEvent.
        :param vehicle_id: The vehicle_id of this SafetyReportHarshEvent.
        """
        self.openapi_types = {
            'harsh_event_type': str,
            'timestamp_ms': int,
            'vehicle_id': int
        }

        self.attribute_map = {
            'harsh_event_type': 'harshEventType',
            'timestamp_ms': 'timestampMs',
            'vehicle_id': 'vehicleId'
        }

        self._harsh_event_type = harsh_event_type
        self._timestamp_ms = timestamp_ms
        self._vehicle_id = vehicle_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SafetyReportHarshEvent':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SafetyReportHarshEvent of this SafetyReportHarshEvent.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def harsh_event_type(self):
        """Gets the harsh_event_type of this SafetyReportHarshEvent.

        Type of the harsh event

        :return: The harsh_event_type of this SafetyReportHarshEvent.
        :rtype: str
        """
        return self._harsh_event_type

    @harsh_event_type.setter
    def harsh_event_type(self, harsh_event_type):
        """Sets the harsh_event_type of this SafetyReportHarshEvent.

        Type of the harsh event

        :param harsh_event_type: The harsh_event_type of this SafetyReportHarshEvent.
        :type harsh_event_type: str
        """

        self._harsh_event_type = harsh_event_type

    @property
    def timestamp_ms(self):
        """Gets the timestamp_ms of this SafetyReportHarshEvent.

        Timestamp that the harsh event occurred in Unix milliseconds since epoch

        :return: The timestamp_ms of this SafetyReportHarshEvent.
        :rtype: int
        """
        return self._timestamp_ms

    @timestamp_ms.setter
    def timestamp_ms(self, timestamp_ms):
        """Sets the timestamp_ms of this SafetyReportHarshEvent.

        Timestamp that the harsh event occurred in Unix milliseconds since epoch

        :param timestamp_ms: The timestamp_ms of this SafetyReportHarshEvent.
        :type timestamp_ms: int
        """

        self._timestamp_ms = timestamp_ms

    @property
    def vehicle_id(self):
        """Gets the vehicle_id of this SafetyReportHarshEvent.

        Vehicle associated with the harsh event

        :return: The vehicle_id of this SafetyReportHarshEvent.
        :rtype: int
        """
        return self._vehicle_id

    @vehicle_id.setter
    def vehicle_id(self, vehicle_id):
        """Sets the vehicle_id of this SafetyReportHarshEvent.

        Vehicle associated with the harsh event

        :param vehicle_id: The vehicle_id of this SafetyReportHarshEvent.
        :type vehicle_id: int
        """

        self._vehicle_id = vehicle_id
