# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TripResponseEndCoordinates(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, latitude: float=None, longitude: float=None):
        """TripResponseEndCoordinates - a model defined in OpenAPI

        :param latitude: The latitude of this TripResponseEndCoordinates.
        :param longitude: The longitude of this TripResponseEndCoordinates.
        """
        self.openapi_types = {
            'latitude': float,
            'longitude': float
        }

        self.attribute_map = {
            'latitude': 'latitude',
            'longitude': 'longitude'
        }

        self._latitude = latitude
        self._longitude = longitude

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TripResponseEndCoordinates':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TripResponse_endCoordinates of this TripResponseEndCoordinates.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self):
        """Gets the latitude of this TripResponseEndCoordinates.


        :return: The latitude of this TripResponseEndCoordinates.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this TripResponseEndCoordinates.


        :param latitude: The latitude of this TripResponseEndCoordinates.
        :type latitude: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this TripResponseEndCoordinates.


        :return: The longitude of this TripResponseEndCoordinates.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this TripResponseEndCoordinates.


        :param longitude: The longitude of this TripResponseEndCoordinates.
        :type longitude: float
        """

        self._longitude = longitude
