# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class VehicleHarshEventResponseLocation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, address: str=None, latitude: str=None, longitude: str=None):
        """VehicleHarshEventResponseLocation - a model defined in OpenAPI

        :param address: The address of this VehicleHarshEventResponseLocation.
        :param latitude: The latitude of this VehicleHarshEventResponseLocation.
        :param longitude: The longitude of this VehicleHarshEventResponseLocation.
        """
        self.openapi_types = {
            'address': str,
            'latitude': str,
            'longitude': str
        }

        self.attribute_map = {
            'address': 'address',
            'latitude': 'latitude',
            'longitude': 'longitude'
        }

        self._address = address
        self._latitude = latitude
        self._longitude = longitude

    @classmethod
    def from_dict(cls, dikt: dict) -> 'VehicleHarshEventResponseLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The VehicleHarshEventResponse_location of this VehicleHarshEventResponseLocation.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self):
        """Gets the address of this VehicleHarshEventResponseLocation.

        Address of location where the harsh event occurred

        :return: The address of this VehicleHarshEventResponseLocation.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this VehicleHarshEventResponseLocation.

        Address of location where the harsh event occurred

        :param address: The address of this VehicleHarshEventResponseLocation.
        :type address: str
        """

        self._address = address

    @property
    def latitude(self):
        """Gets the latitude of this VehicleHarshEventResponseLocation.

        Latitude of location where the harsh event occurred

        :return: The latitude of this VehicleHarshEventResponseLocation.
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this VehicleHarshEventResponseLocation.

        Latitude of location where the harsh event occurred

        :param latitude: The latitude of this VehicleHarshEventResponseLocation.
        :type latitude: str
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this VehicleHarshEventResponseLocation.

        Longitude of location where the harsh event occurred

        :return: The longitude of this VehicleHarshEventResponseLocation.
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this VehicleHarshEventResponseLocation.

        Longitude of location where the harsh event occurred

        :param longitude: The longitude of this VehicleHarshEventResponseLocation.
        :type longitude: str
        """

        self._longitude = longitude
