# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test HumidityResponse")

model.instance <- HumidityResponse$new()

test_that("groupId", {
  # tests for the property `groupId` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`groupId`, "EXPECTED_RESULT")
})

test_that("sensors", {
  # tests for the property `sensors` (HumidityResponseSensors)

  # uncomment below to test the property 
  #expect_equal(model.instance$`sensors`, "EXPECTED_RESULT")
})

