# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DvirBase")

model.instance <- DvirBase$new()

test_that("authorSignature", {
  # tests for the property `authorSignature` (DvirBaseAuthorSignature)

  # uncomment below to test the property 
  #expect_equal(model.instance$`authorSignature`, "EXPECTED_RESULT")
})

test_that("defectsCorrected", {
  # tests for the property `defectsCorrected` (character)
  # Signifies if the defects on the vehicle corrected after the DVIR is done.

  # uncomment below to test the property 
  #expect_equal(model.instance$`defectsCorrected`, "EXPECTED_RESULT")
})

test_that("defectsNeedNotBeCorrected", {
  # tests for the property `defectsNeedNotBeCorrected` (character)
  # Signifies if the defects on this vehicle can be ignored.

  # uncomment below to test the property 
  #expect_equal(model.instance$`defectsNeedNotBeCorrected`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)
  # The id of this DVIR record.

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("inspectionType", {
  # tests for the property `inspectionType` (character)
  # Inspection type of the DVIR.

  # uncomment below to test the property 
  #expect_equal(model.instance$`inspectionType`, "EXPECTED_RESULT")
})

test_that("mechanicNotes", {
  # tests for the property `mechanicNotes` (character)
  # The mechanics notes on the DVIR.

  # uncomment below to test the property 
  #expect_equal(model.instance$`mechanicNotes`, "EXPECTED_RESULT")
})

test_that("mechanicOrAgentSignature", {
  # tests for the property `mechanicOrAgentSignature` (DvirBaseMechanicOrAgentSignature)

  # uncomment below to test the property 
  #expect_equal(model.instance$`mechanicOrAgentSignature`, "EXPECTED_RESULT")
})

test_that("nextDriverSignature", {
  # tests for the property `nextDriverSignature` (DvirBaseNextDriverSignature)

  # uncomment below to test the property 
  #expect_equal(model.instance$`nextDriverSignature`, "EXPECTED_RESULT")
})

test_that("odometerMiles", {
  # tests for the property `odometerMiles` (integer)
  # The odometer reading in miles for the vehicle when the DVIR was done.

  # uncomment below to test the property 
  #expect_equal(model.instance$`odometerMiles`, "EXPECTED_RESULT")
})

test_that("timeMs", {
  # tests for the property `timeMs` (integer)
  # Timestamp of this DVIR in UNIX milliseconds.

  # uncomment below to test the property 
  #expect_equal(model.instance$`timeMs`, "EXPECTED_RESULT")
})

test_that("trailerDefects", {
  # tests for the property `trailerDefects` (DvirBaseTrailerDefects)
  # Defects registered for the trailer which was part of the DVIR.

  # uncomment below to test the property 
  #expect_equal(model.instance$`trailerDefects`, "EXPECTED_RESULT")
})

test_that("trailerId", {
  # tests for the property `trailerId` (integer)
  # The id of the trailer which was part of the DVIR.

  # uncomment below to test the property 
  #expect_equal(model.instance$`trailerId`, "EXPECTED_RESULT")
})

test_that("trailerName", {
  # tests for the property `trailerName` (character)
  # The name of the trailer which was part of the DVIR.

  # uncomment below to test the property 
  #expect_equal(model.instance$`trailerName`, "EXPECTED_RESULT")
})

test_that("vehicle", {
  # tests for the property `vehicle` (DvirBaseVehicle)

  # uncomment below to test the property 
  #expect_equal(model.instance$`vehicle`, "EXPECTED_RESULT")
})

test_that("vehicleCondition", {
  # tests for the property `vehicleCondition` (character)
  # The condition of vechile on which DVIR was done.

  # uncomment below to test the property 
  #expect_equal(model.instance$`vehicleCondition`, "EXPECTED_RESULT")
})

test_that("vehicleDefects", {
  # tests for the property `vehicleDefects` (DvirBaseTrailerDefects)
  # Defects registered for the vehicle which was part of the DVIR.

  # uncomment below to test the property 
  #expect_equal(model.instance$`vehicleDefects`, "EXPECTED_RESULT")
})

