# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test HumidityResponseSensors")

model.instance <- HumidityResponseSensors$new()

test_that("name", {
  # tests for the property `name` (character)
  # Name of the sensor.

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("humidity", {
  # tests for the property `humidity` (integer)
  # Currently reported relative humidity in percent, from 0-100.

  # uncomment below to test the property 
  #expect_equal(model.instance$`humidity`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)
  # ID of the sensor.

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

