export * from './assets.service';
import { AssetsService } from './assets.service';
export * from './drivers.service';
import { DriversService } from './drivers.service';
export * from './fleet.service';
import { FleetService } from './fleet.service';
export * from './industrial.service';
import { IndustrialService } from './industrial.service';
export * from './routes.service';
import { RoutesService } from './routes.service';
export * from './safety.service';
import { SafetyService } from './safety.service';
export * from './sensors.service';
import { SensorsService } from './sensors.service';
export * from './tags.service';
import { TagsService } from './tags.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AssetsService, DriversService, FleetService, IndustrialService, RoutesService, SafetyService, SensorsService, TagsService, UsersService];
