# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from samsara.models.base_model_ import Model
from samsara.models.document_field_type import DocumentFieldType  # noqa: F401,E501
from samsara import util


class DocumentFieldTypes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """DocumentFieldTypes - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentFieldTypes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DocumentFieldTypes of this DocumentFieldTypes.  # noqa: E501
        :rtype: DocumentFieldTypes
        """
        return util.deserialize_model(dikt, cls)
