/**
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of AssetCurrentLocationsResponse
 *
 * @constructor
 */
angular.module('SamsaraAPILib')
    .factory('AssetCurrentLocationsResponse', ['BaseModel', AssetCurrentLocationsResponseModel]);

    function AssetCurrentLocationsResponseModel(BaseModel) {
        var AssetCurrentLocationsResponse = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.cable = this.getValue(obj.cable);
            this.engineHours = this.getValue(obj.engineHours);
            this.id = this.getValue(obj.id);
            this.location = this.getValue(obj.location);
            this.name = this.getValue(obj.name);
        };

        AssetCurrentLocationsResponse.prototype = new BaseModel();
        AssetCurrentLocationsResponse.prototype.constructor = AssetCurrentLocationsResponse;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        AssetCurrentLocationsResponse.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'cable', realName: 'cable', array: true, type: 'Cable' },
                { name: 'engineHours', realName: 'engineHours' },
                { name: 'id', realName: 'id' },
                { name: 'location', realName: 'location', array: true, type: 'AssetCurrentLocation' },
                { name: 'name', realName: 'name' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        AssetCurrentLocationsResponse.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The cable connected to the asset
         *
         * @return {array|null}
         */
        AssetCurrentLocationsResponse.prototype.getCable = function () {
            return this.cable;
        };
    
        /**
         * Setter for Cable
         * 
         * @param {array|null} value 
         */
        AssetCurrentLocationsResponse.prototype.setCable = function (value) {
            this.cable = value;
        };
    
        /**
         * Engine hours
         *
         * @return {int|null}
         */
        AssetCurrentLocationsResponse.prototype.getEngineHours = function () {
            return this.engineHours;
        };
    
        /**
         * Setter for EngineHours
         * 
         * @param {int|null} value 
         */
        AssetCurrentLocationsResponse.prototype.setEngineHours = function (value) {
            this.engineHours = value;
        };
    
        /**
         * Asset ID
         *
         * @return {long}
         */
        AssetCurrentLocationsResponse.prototype.getId = function () {
            return this.id;
        };
    
        /**
         * Setter for Id
         * 
         * @param {long} value 
         */
        AssetCurrentLocationsResponse.prototype.setId = function (value) {
            this.id = value;
        };
    
        /**
         * Current location of an asset
         *
         * @return {array|null}
         */
        AssetCurrentLocationsResponse.prototype.getLocation = function () {
            return this.location;
        };
    
        /**
         * Setter for Location
         * 
         * @param {array|null} value 
         */
        AssetCurrentLocationsResponse.prototype.setLocation = function (value) {
            this.location = value;
        };
    
        /**
         * Asset name
         *
         * @return {string|null}
         */
        AssetCurrentLocationsResponse.prototype.getName = function () {
            return this.name;
        };
    
        /**
         * Setter for Name
         * 
         * @param {string|null} value 
         */
        AssetCurrentLocationsResponse.prototype.setName = function (value) {
            this.name = value;
        };
    
        return AssetCurrentLocationsResponse;
    }

}(angular));
