/**
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of EngineState
 *
 * @constructor
 */
angular.module('SamsaraAPILib')
    .factory('EngineState', ['BaseModel', EngineStateModel]);

    function EngineStateModel(BaseModel) {
        var EngineState = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.timeMs = this.getValue(obj.timeMs);
            this.value = this.getValue(obj.value);
        };

        EngineState.prototype = new BaseModel();
        EngineState.prototype.constructor = EngineState;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        EngineState.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'timeMs', realName: 'timeMs' },
                { name: 'value', realName: 'value' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        EngineState.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * Timestamp in Unix epoch milliseconds.
         *
         * @return {long}
         */
        EngineState.prototype.getTimeMs = function () {
            return this.timeMs;
        };
    
        /**
         * Setter for TimeMs
         * 
         * @param {long} value 
         */
        EngineState.prototype.setTimeMs = function (value) {
            this.timeMs = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {ValueEnum}
         */
        EngineState.prototype.getValue = function () {
            return this.value;
        };
    
        /**
         * Setter for Value
         * 
         * @param {ValueEnum} value 
         */
        EngineState.prototype.setValue = function (value) {
            this.value = value;
        };
    
        return EngineState;
    }

}(angular));
