/**
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of GetSensorsResponse
 *
 * @constructor
 */
angular.module('SamsaraAPILib')
    .factory('GetSensorsResponse', ['BaseModel', GetSensorsResponseModel]);

    function GetSensorsResponseModel(BaseModel) {
        var GetSensorsResponse = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.sensors = this.getValue(obj.sensors);
        };

        GetSensorsResponse.prototype = new BaseModel();
        GetSensorsResponse.prototype.constructor = GetSensorsResponse;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        GetSensorsResponse.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'sensors', realName: 'sensors', array: true, type: 'Sensor' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        GetSensorsResponse.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        GetSensorsResponse.prototype.getSensors = function () {
            return this.sensors;
        };
    
        /**
         * Setter for Sensors
         * 
         * @param {array|null} value 
         */
        GetSensorsResponse.prototype.setSensors = function (value) {
            this.sensors = value;
        };
    
        return GetSensorsResponse;
    }

}(angular));
