/**
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of HosAuthenticationLogsResponse
 *
 * @constructor
 */
angular.module('SamsaraAPILib')
    .factory('HosAuthenticationLogsResponse', ['BaseModel', HosAuthenticationLogsResponseModel]);

    function HosAuthenticationLogsResponseModel(BaseModel) {
        var HosAuthenticationLogsResponse = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.authenticationLogs = this.getValue(obj.authenticationLogs);
        };

        HosAuthenticationLogsResponse.prototype = new BaseModel();
        HosAuthenticationLogsResponse.prototype.constructor = HosAuthenticationLogsResponse;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        HosAuthenticationLogsResponse.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'authenticationLogs', realName: 'authenticationLogs', array: true, type: 'AuthenticationLog' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        HosAuthenticationLogsResponse.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        HosAuthenticationLogsResponse.prototype.getAuthenticationLogs = function () {
            return this.authenticationLogs;
        };
    
        /**
         * Setter for AuthenticationLogs
         * 
         * @param {array|null} value 
         */
        HosAuthenticationLogsResponse.prototype.setAuthenticationLogs = function (value) {
            this.authenticationLogs = value;
        };
    
        return HosAuthenticationLogsResponse;
    }

}(angular));
