/**
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of HosAuthenticationLogsParam
 *
 * @constructor
 */
angular.module('SamsaraAPILib')
    .factory('HosAuthenticationLogsParam', ['BaseModel', HosAuthenticationLogsParamModel]);

    function HosAuthenticationLogsParamModel(BaseModel) {
        var HosAuthenticationLogsParam = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.driverId = this.getValue(obj.driverId);
            this.endMs = this.getValue(obj.endMs);
            this.groupId = this.getValue(obj.groupId);
            this.startMs = this.getValue(obj.startMs);
        };

        HosAuthenticationLogsParam.prototype = new BaseModel();
        HosAuthenticationLogsParam.prototype.constructor = HosAuthenticationLogsParam;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        HosAuthenticationLogsParam.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'driverId', realName: 'driverId' },
                { name: 'endMs', realName: 'endMs' },
                { name: 'groupId', realName: 'groupId' },
                { name: 'startMs', realName: 'startMs' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        HosAuthenticationLogsParam.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * Driver ID to query.
         *
         * @return {long}
         */
        HosAuthenticationLogsParam.prototype.getDriverId = function () {
            return this.driverId;
        };
    
        /**
         * Setter for DriverId
         * 
         * @param {long} value 
         */
        HosAuthenticationLogsParam.prototype.setDriverId = function (value) {
            this.driverId = value;
        };
    
        /**
         * End of the time range, specified in milliseconds UNIX time.
         *
         * @return {long}
         */
        HosAuthenticationLogsParam.prototype.getEndMs = function () {
            return this.endMs;
        };
    
        /**
         * Setter for EndMs
         * 
         * @param {long} value 
         */
        HosAuthenticationLogsParam.prototype.setEndMs = function (value) {
            this.endMs = value;
        };
    
        /**
         * Group ID to query.
         *
         * @return {long}
         */
        HosAuthenticationLogsParam.prototype.getGroupId = function () {
            return this.groupId;
        };
    
        /**
         * Setter for GroupId
         * 
         * @param {long} value 
         */
        HosAuthenticationLogsParam.prototype.setGroupId = function (value) {
            this.groupId = value;
        };
    
        /**
         * Beginning of the time range, specified in milliseconds UNIX time.
         *
         * @return {long}
         */
        HosAuthenticationLogsParam.prototype.getStartMs = function () {
            return this.startMs;
        };
    
        /**
         * Setter for StartMs
         * 
         * @param {long} value 
         */
        HosAuthenticationLogsParam.prototype.setStartMs = function (value) {
            this.startMs = value;
        };
    
        return HosAuthenticationLogsParam;
    }

}(angular));
