/**
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ListFleetResponse
 *
 * @constructor
 */
angular.module('SamsaraAPILib')
    .factory('ListFleetResponse', ['BaseModel', ListFleetResponseModel]);

    function ListFleetResponseModel(BaseModel) {
        var ListFleetResponse = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.groupId = this.getValue(obj.groupId);
            this.pagination = this.getValue(obj.pagination);
            this.vehicles = this.getValue(obj.vehicles);
        };

        ListFleetResponse.prototype = new BaseModel();
        ListFleetResponse.prototype.constructor = ListFleetResponse;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        ListFleetResponse.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'groupId', realName: 'groupId' },
                { name: 'pagination', realName: 'pagination', type: 'Pagination' },
                { name: 'vehicles', realName: 'vehicles', array: true, type: 'Vehicle' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        ListFleetResponse.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * Group ID to query.
         *
         * @return {long|null}
         */
        ListFleetResponse.prototype.getGroupId = function () {
            return this.groupId;
        };
    
        /**
         * Setter for GroupId
         * 
         * @param {long|null} value 
         */
        ListFleetResponse.prototype.setGroupId = function (value) {
            this.groupId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Pagination|null}
         */
        ListFleetResponse.prototype.getPagination = function () {
            return this.pagination;
        };
    
        /**
         * Setter for Pagination
         * 
         * @param {Pagination|null} value 
         */
        ListFleetResponse.prototype.setPagination = function (value) {
            this.pagination = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        ListFleetResponse.prototype.getVehicles = function () {
            return this.vehicles;
        };
    
        /**
         * Setter for Vehicles
         * 
         * @param {array|null} value 
         */
        ListFleetResponse.prototype.setVehicles = function (value) {
            this.vehicles = value;
        };
    
        return ListFleetResponse;
    }

}(angular));
