/**
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of TaggedAddress
 *
 * @constructor
 */
angular.module('SamsaraAPILib')
    .factory('TaggedAddress', ['BaseModel', TaggedAddressModel]);

    function TaggedAddressModel(BaseModel) {
        var TaggedAddress = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.id = this.getValue(obj.id);
            this.name = this.getValue(obj.name);
        };

        TaggedAddress.prototype = new BaseModel();
        TaggedAddress.prototype.constructor = TaggedAddress;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        TaggedAddress.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'id', realName: 'id' },
                { name: 'name', realName: 'name' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        TaggedAddress.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The ID of the address being tagged.
         *
         * @return {long}
         */
        TaggedAddress.prototype.getId = function () {
            return this.id;
        };
    
        /**
         * Setter for Id
         * 
         * @param {long} value 
         */
        TaggedAddress.prototype.setId = function (value) {
            this.id = value;
        };
    
        /**
         * Name of the address being tagged.
         *
         * @return {string|null}
         */
        TaggedAddress.prototype.getName = function () {
            return this.name;
        };
    
        /**
         * Setter for Name
         * 
         * @param {string|null} value 
         */
        TaggedAddress.prototype.setName = function (value) {
            this.name = value;
        };
    
        return TaggedAddress;
    }

}(angular));
