/*
 * SamsaraAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SamsaraAPI.PCL;
using SamsaraAPI.PCL.Utilities;


namespace SamsaraAPI.PCL.Models
{
    public class Day : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? activeHours;
        private long? activeMs;
        private bool? certified;
        private long? certifiedAtMs;
        private double? distanceMiles;
        private long? endMs;
        private long? startMs;
        private object trailerIds;
        private object vehicleIds;

        /// <summary>
        /// Hours spent on duty or driving, rounded to two decimal places.
        /// </summary>
        [JsonProperty("activeHours")]
        public double? ActiveHours 
        { 
            get 
            {
                return this.activeHours; 
            } 
            set 
            {
                this.activeHours = value;
                onPropertyChanged("ActiveHours");
            }
        }

        /// <summary>
        /// Milliseconds spent on duty or driving.
        /// </summary>
        [JsonProperty("activeMs")]
        public long? ActiveMs 
        { 
            get 
            {
                return this.activeMs; 
            } 
            set 
            {
                this.activeMs = value;
                onPropertyChanged("ActiveMs");
            }
        }

        /// <summary>
        /// Whether this HOS day chart was certified by the driver.
        /// </summary>
        [JsonProperty("certified")]
        public bool? Certified 
        { 
            get 
            {
                return this.certified; 
            } 
            set 
            {
                this.certified = value;
                onPropertyChanged("Certified");
            }
        }

        /// <summary>
        /// Unix epoch time (in ms) of time when this chart was certified. If this chart is uncertified, 0.
        /// </summary>
        [JsonProperty("certifiedAtMs")]
        public long? CertifiedAtMs 
        { 
            get 
            {
                return this.certifiedAtMs; 
            } 
            set 
            {
                this.certifiedAtMs = value;
                onPropertyChanged("CertifiedAtMs");
            }
        }

        /// <summary>
        /// Distance driven in miles, rounded to two decimal places.
        /// </summary>
        [JsonProperty("distanceMiles")]
        public double? DistanceMiles 
        { 
            get 
            {
                return this.distanceMiles; 
            } 
            set 
            {
                this.distanceMiles = value;
                onPropertyChanged("DistanceMiles");
            }
        }

        /// <summary>
        /// End of the HOS day, specified in milliseconds UNIX time.
        /// </summary>
        [JsonProperty("endMs")]
        public long? EndMs 
        { 
            get 
            {
                return this.endMs; 
            } 
            set 
            {
                this.endMs = value;
                onPropertyChanged("EndMs");
            }
        }

        /// <summary>
        /// End of the HOS day, specified in milliseconds UNIX time.
        /// </summary>
        [JsonProperty("startMs")]
        public long? StartMs 
        { 
            get 
            {
                return this.startMs; 
            } 
            set 
            {
                this.startMs = value;
                onPropertyChanged("StartMs");
            }
        }

        /// <summary>
        /// List of trailer ID's associated with the driver for the day.
        /// </summary>
        [JsonProperty("trailerIds")]
        public object TrailerIds 
        { 
            get 
            {
                return this.trailerIds; 
            } 
            set 
            {
                this.trailerIds = value;
                onPropertyChanged("TrailerIds");
            }
        }

        /// <summary>
        /// List of vehicle ID's associated with the driver for the day.
        /// </summary>
        [JsonProperty("vehicleIds")]
        public object VehicleIds 
        { 
            get 
            {
                return this.vehicleIds; 
            } 
            set 
            {
                this.vehicleIds = value;
                onPropertyChanged("VehicleIds");
            }
        }
    }
} 