/*
 * SamsaraAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SamsaraAPI.PCL;
using SamsaraAPI.PCL.Utilities;


namespace SamsaraAPI.PCL.Models
{
    public class DispatchRouteHistoricalEntry : BaseModel 
    {
        // These fields hold the values for the public properties.
        private long? changedAtMs;
        private Models.DispatchRoute route;

        /// <summary>
        /// Timestamp that the route was updated, represented as Unix milliseconds since epoch.
        /// </summary>
        [JsonProperty("changed_at_ms")]
        public long? ChangedAtMs 
        { 
            get 
            {
                return this.changedAtMs; 
            } 
            set 
            {
                this.changedAtMs = value;
                onPropertyChanged("ChangedAtMs");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("route")]
        public Models.DispatchRoute Route 
        { 
            get 
            {
                return this.route; 
            } 
            set 
            {
                this.route = value;
                onPropertyChanged("Route");
            }
        }
    }
} 