/*
 * SamsaraAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SamsaraAPI.PCL;
using SamsaraAPI.PCL.Utilities;


namespace SamsaraAPI.PCL.Models
{
    public class DriversSummaryResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.Summary> summaries;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Summaries")]
        public List<Models.Summary> Summaries 
        { 
            get 
            {
                return this.summaries; 
            } 
            set 
            {
                this.summaries = value;
                onPropertyChanged("Summaries");
            }
        }
    }
} 