/*
 * SamsaraAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SamsaraAPI.PCL;
using SamsaraAPI.PCL.Utilities;


namespace SamsaraAPI.PCL.Models
{
    public class Tag : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.TaggedAddress> addresses;
        private List<Models.TaggedAsset> assets;
        private List<Models.TaggedDriver> drivers;
        private long? groupId;
        private long id;
        private List<Models.TaggedMachine> machines;
        private string name;
        private long? parentTagId;
        private List<Models.TaggedSensor> sensors;
        private List<Models.TaggedVehicle> vehicles;

        /// <summary>
        /// The addresses that belong to this tag.
        /// </summary>
        [JsonProperty("addresses")]
        public List<Models.TaggedAddress> Addresses 
        { 
            get 
            {
                return this.addresses; 
            } 
            set 
            {
                this.addresses = value;
                onPropertyChanged("Addresses");
            }
        }

        /// <summary>
        /// The assets that belong to this tag.
        /// </summary>
        [JsonProperty("assets")]
        public List<Models.TaggedAsset> Assets 
        { 
            get 
            {
                return this.assets; 
            } 
            set 
            {
                this.assets = value;
                onPropertyChanged("Assets");
            }
        }

        /// <summary>
        /// The drivers that belong to this tag.
        /// </summary>
        [JsonProperty("drivers")]
        public List<Models.TaggedDriver> Drivers 
        { 
            get 
            {
                return this.drivers; 
            } 
            set 
            {
                this.drivers = value;
                onPropertyChanged("Drivers");
            }
        }

        /// <summary>
        /// The GroupID that this tag belongs to.
        /// </summary>
        [JsonProperty("groupId")]
        public long? GroupId 
        { 
            get 
            {
                return this.groupId; 
            } 
            set 
            {
                this.groupId = value;
                onPropertyChanged("GroupId");
            }
        }

        /// <summary>
        /// The ID of this tag.
        /// </summary>
        [JsonProperty("id")]
        public long Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The machines that belong to this tag.
        /// </summary>
        [JsonProperty("machines")]
        public List<Models.TaggedMachine> Machines 
        { 
            get 
            {
                return this.machines; 
            } 
            set 
            {
                this.machines = value;
                onPropertyChanged("Machines");
            }
        }

        /// <summary>
        /// Name of this tag.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// If this tag is part a hierarchical tag tree as a child tag, the parentTagId is the ID of this tag's parent tag.
        /// </summary>
        [JsonProperty("parentTagId")]
        public long? ParentTagId 
        { 
            get 
            {
                return this.parentTagId; 
            } 
            set 
            {
                this.parentTagId = value;
                onPropertyChanged("ParentTagId");
            }
        }

        /// <summary>
        /// The sensors that belong to this tag.
        /// </summary>
        [JsonProperty("sensors")]
        public List<Models.TaggedSensor> Sensors 
        { 
            get 
            {
                return this.sensors; 
            } 
            set 
            {
                this.sensors = value;
                onPropertyChanged("Sensors");
            }
        }

        /// <summary>
        /// The vehicles that belong to this tag.
        /// </summary>
        [JsonProperty("vehicles")]
        public List<Models.TaggedVehicle> Vehicles 
        { 
            get 
            {
                return this.vehicles; 
            } 
            set 
            {
                this.vehicles = value;
                onPropertyChanged("Vehicles");
            }
        }
    }
} 