/*
 * SamsaraAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SamsaraAPI.PCL;
using SamsaraAPI.PCL.Utilities;


namespace SamsaraAPI.PCL.Models
{
    public class TagUpdate : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.TaggedAssetBase> assets;
        private List<Models.TaggedDriverBase> drivers;
        private List<Models.TaggedMachineBase> machines;
        private string name;
        private long? parentTagId;
        private List<Models.TaggedSensorBase> sensors;
        private List<Models.TaggedVehicleBase> vehicles;

        /// <summary>
        /// The assets that belong to this tag.
        /// </summary>
        [JsonProperty("assets")]
        public List<Models.TaggedAssetBase> Assets 
        { 
            get 
            {
                return this.assets; 
            } 
            set 
            {
                this.assets = value;
                onPropertyChanged("Assets");
            }
        }

        /// <summary>
        /// The drivers that belong to this tag.
        /// </summary>
        [JsonProperty("drivers")]
        public List<Models.TaggedDriverBase> Drivers 
        { 
            get 
            {
                return this.drivers; 
            } 
            set 
            {
                this.drivers = value;
                onPropertyChanged("Drivers");
            }
        }

        /// <summary>
        /// The machines that belong to this tag.
        /// </summary>
        [JsonProperty("machines")]
        public List<Models.TaggedMachineBase> Machines 
        { 
            get 
            {
                return this.machines; 
            } 
            set 
            {
                this.machines = value;
                onPropertyChanged("Machines");
            }
        }

        /// <summary>
        /// Updated name of this tag.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// If this tag is part a hierarchical tag tree as a child tag, the parentTagId is the ID of this tag's parent tag.
        /// </summary>
        [JsonProperty("parentTagId")]
        public long? ParentTagId 
        { 
            get 
            {
                return this.parentTagId; 
            } 
            set 
            {
                this.parentTagId = value;
                onPropertyChanged("ParentTagId");
            }
        }

        /// <summary>
        /// The sensors that belong to this tag.
        /// </summary>
        [JsonProperty("sensors")]
        public List<Models.TaggedSensorBase> Sensors 
        { 
            get 
            {
                return this.sensors; 
            } 
            set 
            {
                this.sensors = value;
                onPropertyChanged("Sensors");
            }
        }

        /// <summary>
        /// The vehicles that belong to this tag.
        /// </summary>
        [JsonProperty("vehicles")]
        public List<Models.TaggedVehicleBase> Vehicles 
        { 
            get 
            {
                return this.vehicles; 
            } 
            set 
            {
                this.vehicles = value;
                onPropertyChanged("Vehicles");
            }
        }
    }
} 