/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.3-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AddressParam;
import io.swagger.model.AllRouteJobUpdates;
import io.swagger.model.AssetLocationResponse;
import io.swagger.model.AssetReeferResponse;
import io.swagger.model.CreateDvirParam;
import io.swagger.model.CurrentDriver;
import io.swagger.model.Data;
import io.swagger.model.DispatchRoute;
import io.swagger.model.DispatchRouteCreate;
import io.swagger.model.DispatchRouteHistory;
import io.swagger.model.DispatchRoutes;
import io.swagger.model.Document;
import io.swagger.model.DocumentCreate;
import io.swagger.model.DocumentTypes;
import io.swagger.model.Documents;
import io.swagger.model.Driver;
import io.swagger.model.DriverDailyLogResponse;
import io.swagger.model.DriverForCreate;
import io.swagger.model.DriverSafetyScoreResponse;
import io.swagger.model.DriversResponse;
import io.swagger.model.DriversSummaryParam;
import io.swagger.model.DriversSummaryResponse;
import io.swagger.model.DvirBase;
import io.swagger.model.DvirListResponse;
import io.swagger.model.FleetVehicleLocations;
import io.swagger.model.FleetVehicleResponse;
import io.swagger.model.FleetVehiclesLocations;
import io.swagger.model.GroupDriversParam;
import io.swagger.model.GroupParam;
import io.swagger.model.HosAuthenticationLogsParam;
import io.swagger.model.HosAuthenticationLogsResponse;
import io.swagger.model.HosLogsParam;
import io.swagger.model.HosLogsParam1;
import io.swagger.model.HosLogsParam2;
import io.swagger.model.HosLogsResponse;
import io.swagger.model.HosLogsSummaryResponse;
import io.swagger.model.InlineResponse200;
import io.swagger.model.InlineResponse2001;
import io.swagger.model.InlineResponse2002;
import io.swagger.model.InlineResponse2003;
import io.swagger.model.InlineResponse2004;
import io.swagger.model.InlineResponse2005;
import io.swagger.model.ReactivateDriverParam;
import io.swagger.model.TripResponse;
import io.swagger.model.TripsParam;
import io.swagger.model.VehicleHarshEventResponse;
import io.swagger.model.VehicleSafetyScoreResponse;
import io.swagger.model.VehicleUpdateParam;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-03-01T04:20:34.312Z")

@Api(value = "fleet", description = "the fleet API")
public interface FleetApi {

    @ApiOperation(value = "/fleet/add_address", nickname = "addFleetAddress", notes = "This method adds an address book entry to the specified group.", tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Address was successfully added. No response body is returned."),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/add_address",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addFleetAddress(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "" ,required=true )  @Valid @RequestBody AddressParam addressParam);


    @ApiOperation(value = "/fleet/dispatch/routes", nickname = "createDispatchRoute", notes = "Create a new dispatch route.", response = DispatchRoute.class, tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Created route object including the new route ID.", response = DispatchRoute.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/dispatch/routes",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<DispatchRoute> createDispatchRoute(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "" ,required=true )  @Valid @RequestBody DispatchRouteCreate createDispatchRouteParams);


    @ApiOperation(value = "/fleet/drivers/create", nickname = "createDriver", notes = "Create a new driver.", response = Driver.class, tags={ "Fleet","Drivers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns the successfully created the driver.", response = Driver.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/create",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Driver> createDriver(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Driver creation body" ,required=true )  @Valid @RequestBody DriverForCreate createDriverParam);


    @ApiOperation(value = "/fleet/drivers/{driver_id:[0-9]+}/dispatch/routes", nickname = "createDriverDispatchRoute", notes = "Create a new dispatch route for the driver with driver_id.", response = DispatchRoute.class, tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Created route object including the new route ID.", response = DispatchRoute.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/{driver_id}/dispatch/routes",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<DispatchRoute> createDriverDispatchRoute(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the driver with the associated routes.",required=true) @PathVariable("driver_id") Long driverId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody DispatchRouteCreate createDispatchRouteParams);


    @ApiOperation(value = "/fleet/drivers/{driver_id:[0-9]+}/documents", nickname = "createDriverDocument", notes = "Create a driver document for the given driver.", response = Document.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns the created document.", response = Document.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/{driver_id}/documents",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Document> createDriverDocument(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the driver for whom the document is created.",required=true) @PathVariable("driver_id") Long driverId,@ApiParam(value = "To create a document for a given document type, the document type's uuid needs to be passed in to documentTypeUuid. The list of fields passed in should match the document type’s list of field types in the correct order. In other words, a field's valueType and value (i.e. only one of: stringValue, numberValue, or photoValue) at index _i_ should match with the document field type’s valueType at index _i_." ,required=true )  @Valid @RequestBody DocumentCreate createDocumentParams);


    @ApiOperation(value = "/fleet/maintenance/dvirs", nickname = "createDvir", notes = "Create a new dvir, marking a vehicle or trailer safe or unsafe.", response = DvirBase.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Newly created DVIR.", response = DvirBase.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/maintenance/dvirs",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<DvirBase> createDvir(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "DVIR creation body" ,required=true )  @Valid @RequestBody CreateDvirParam createDvirParam);


    @ApiOperation(value = "/fleet/vehicles/{vehicle_id:[0-9]+}/dispatch/routes", nickname = "createVehicleDispatchRoute", notes = "Create a new dispatch route for the vehicle with vehicle_id.", response = DispatchRoute.class, tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Created route object including the new route ID.", response = DispatchRoute.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/vehicles/{vehicle_id}/dispatch/routes",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<DispatchRoute> createVehicleDispatchRoute(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the vehicle with the associated routes.",required=true) @PathVariable("vehicle_id") Long vehicleId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody DispatchRouteCreate createDispatchRouteParams);


    @ApiOperation(value = "/fleet/drivers/{driver_id:[0-9]+ | external_id:[a-zA-Z0-9]+}", nickname = "deactivateDriver", notes = "Deactivate a driver with the given id.", tags={ "Fleet","Drivers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully deactivated the driver, which is now referenced by /fleet/drivers/inactive/{driver_id}."),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/{driver_id_or_external_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deactivateDriver(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the driver.  This must be either the numeric ID generated by Samsara or the external ID of the driver.  External IDs are customer specified key-value pairs.",required=true) @PathVariable("driver_id_or_external_id") String driverIdOrExternalId);


    @ApiOperation(value = "/fleet/dispatch/routes/{route_id:[0-9]+}/", nickname = "deleteDispatchRouteById", notes = "Delete a dispatch route and its associated jobs.", tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully deleted the dispatch route. No response body is returned."),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/dispatch/routes/{route_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteDispatchRouteById(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the dispatch route.",required=true) @PathVariable("route_id") Long routeId);


    @ApiOperation(value = "/fleet/dispatch/routes", nickname = "fetchAllDispatchRoutes", notes = "Fetch all of the dispatch routes for the group.", response = DispatchRoutes.class, tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "All dispatch route objects for the group.", response = DispatchRoutes.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/dispatch/routes",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<DispatchRoutes> fetchAllDispatchRoutes(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Optional group ID if the organization has multiple groups (uncommon).") @Valid @RequestParam(value = "group_id", required = false) Long groupId,@ApiParam(value = "Time in unix milliseconds that represents the oldest routes to return. Used in combination with duration. Defaults to now.") @Valid @RequestParam(value = "end_time", required = false) Long endTime,@ApiParam(value = "Time in milliseconds that represents the duration before end_time to query. Defaults to 24 hours.") @Valid @RequestParam(value = "duration", required = false) Long duration);


    @ApiOperation(value = "/fleet/dispatch/routes/job_updates", nickname = "fetchAllRouteJobUpdates", notes = "Fetch all updates to a job including route data in the last 24 hours or subsequent to an sequence ID", response = AllRouteJobUpdates.class, tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "All job updates on routes.", response = AllRouteJobUpdates.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/dispatch/routes/job_updates",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<AllRouteJobUpdates> fetchAllRouteJobUpdates(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Optional group ID if the organization has multiple groups (uncommon).") @Valid @RequestParam(value = "group_id", required = false) Long groupId,@ApiParam(value = "Sequence ID from the response payload of the last request. Defaults to fetching updates from last 24 hours.") @Valid @RequestParam(value = "sequence_id", required = false) String sequenceId,@ApiParam(value = "Optionally set include=route to include route object in response payload.") @Valid @RequestParam(value = "include", required = false) String include);


    @ApiOperation(value = "/fleet/assets/locations", nickname = "getAllAssetCurrentLocations", notes = "Fetch current locations of all assets for the group.", response = InlineResponse2001.class, tags={ "Fleet","Assets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of assets and their current locations.", response = InlineResponse2001.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/assets/locations",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<InlineResponse2001> getAllAssetCurrentLocations(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Optional group ID if the organization has multiple groups (uncommon).") @Valid @RequestParam(value = "group_id", required = false) Long groupId);


    @ApiOperation(value = "/fleet/assets", nickname = "getAllAssets", notes = "Fetch all of the assets for the group.", response = InlineResponse200.class, tags={ "Fleet","Assets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of assets.", response = InlineResponse200.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/assets",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<InlineResponse200> getAllAssets(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Optional group ID if the organization has multiple groups (uncommon).") @Valid @RequestParam(value = "group_id", required = false) Long groupId);


    @ApiOperation(value = "/fleet/drivers/inactive", nickname = "getAllDeactivatedDrivers", notes = "Fetch all deactivated drivers for the group.", response = Driver.class, responseContainer = "List", tags={ "Fleet","Drivers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns an array of all deactivated drivers for the group. Deactivated drivers are referenced at /fleet/drivers/inactive/{driver_id}", response = Driver.class, responseContainer = "List"),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/inactive",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Driver>> getAllDeactivatedDrivers(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Optional group ID if the organization has multiple groups (uncommon).") @Valid @RequestParam(value = "group_id", required = false) Long groupId);


    @ApiOperation(value = "/fleet/assets/{assetId:[0-9]+}/locations", nickname = "getAssetLocation", notes = "Fetch the historical locations for the asset.", response = AssetLocationResponse.class, tags={ "Fleet","Assets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Asset location details.", response = AssetLocationResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/assets/{asset_id}/locations",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<AssetLocationResponse> getAssetLocation(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the asset",required=true) @PathVariable("asset_id") Long assetId,@NotNull @ApiParam(value = "Timestamp in milliseconds representing the start of the period to fetch, inclusive. Used in combination with endMs.", required = true) @Valid @RequestParam(value = "startMs", required = true) Long startMs,@NotNull @ApiParam(value = "Timestamp in milliseconds representing the end of the period to fetch, inclusive. Used in combination with startMs.", required = true) @Valid @RequestParam(value = "endMs", required = true) Long endMs);


    @ApiOperation(value = "/fleet/assets/{assetId:[0-9]+}/reefer", nickname = "getAssetReefer", notes = "Fetch the reefer-specific stats of an asset.", response = AssetReeferResponse.class, tags={ "Fleet","Assets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Reefer-specific asset details.", response = AssetReeferResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/assets/{asset_id}/reefer",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<AssetReeferResponse> getAssetReefer(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the asset",required=true) @PathVariable("asset_id") Long assetId,@NotNull @ApiParam(value = "Timestamp in milliseconds representing the start of the period to fetch, inclusive. Used in combination with endMs.", required = true) @Valid @RequestParam(value = "startMs", required = true) Long startMs,@NotNull @ApiParam(value = "Timestamp in milliseconds representing the end of the period to fetch, inclusive. Used in combination with startMs.", required = true) @Valid @RequestParam(value = "endMs", required = true) Long endMs);


    @ApiOperation(value = "/fleet/drivers/inactive/{driver_id:[0-9]+ | external_id:[a-zA-Z0-9]+}", nickname = "getDeactivatedDriverById", notes = "Fetch deactivated driver by id.", response = Driver.class, tags={ "Fleet","Drivers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns the deactivated driver with the given driver_id.", response = Driver.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/inactive/{driver_id_or_external_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Driver> getDeactivatedDriverById(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the driver.  This must be either the numeric ID generated by Samsara or the external ID of the driver.  External IDs are customer specified key-value pairs.",required=true) @PathVariable("driver_id_or_external_id") String driverIdOrExternalId);


    @ApiOperation(value = "/fleet/dispatch/routes/{route_id:[0-9]+}", nickname = "getDispatchRouteById", notes = "Fetch a dispatch route by id.", response = DispatchRoute.class, tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The dispatch route corresponding to route_id.", response = DispatchRoute.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/dispatch/routes/{route_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<DispatchRoute> getDispatchRouteById(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the dispatch route.",required=true) @PathVariable("route_id") Long routeId);


    @ApiOperation(value = "/fleet/dispatch/routes/{route_id:[0-9]+}/history", nickname = "getDispatchRouteHistory", notes = "Fetch the history of a dispatch route.", response = DispatchRouteHistory.class, tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The historical route state changes between start_time and end_time.", response = DispatchRouteHistory.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/dispatch/routes/{route_id}/history",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<DispatchRouteHistory> getDispatchRouteHistory(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the route with history.",required=true) @PathVariable("route_id") Long routeId,@ApiParam(value = "Timestamp representing the start of the period to fetch, inclusive. Used in combination with end_time. Defaults to 0.") @Valid @RequestParam(value = "start_time", required = false) Long startTime,@ApiParam(value = "Timestamp representing the end of the period to fetch, inclusive. Used in combination with start_time. Defaults to nowMs.") @Valid @RequestParam(value = "end_time", required = false) Long endTime);


    @ApiOperation(value = "/fleet/drivers/{driver_id:[0-9]+}/dispatch/routes", nickname = "getDispatchRoutesByDriverId", notes = "Fetch all of the dispatch routes for a given driver.", response = DispatchRoutes.class, tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns the dispatch routes for the given driver_id.", response = DispatchRoutes.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/{driver_id}/dispatch/routes",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<DispatchRoutes> getDispatchRoutesByDriverId(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the driver with the associated routes.",required=true) @PathVariable("driver_id") Long driverId,@ApiParam(value = "Time in unix milliseconds that represents the oldest routes to return. Used in combination with duration. Defaults to now.") @Valid @RequestParam(value = "end_time", required = false) Long endTime,@ApiParam(value = "Time in milliseconds that represents the duration before end_time to query. Defaults to 24 hours.") @Valid @RequestParam(value = "duration", required = false) Long duration);


    @ApiOperation(value = "/fleet/vehicles/{vehicle_id:[0-9]+}/dispatch/routes", nickname = "getDispatchRoutesByVehicleId", notes = "Fetch all of the dispatch routes for a given vehicle.", response = DispatchRoutes.class, tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns all of the dispatch routes for the given vehicle_id.", response = DispatchRoutes.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/vehicles/{vehicle_id}/dispatch/routes",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<DispatchRoutes> getDispatchRoutesByVehicleId(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the vehicle with the associated routes.",required=true) @PathVariable("vehicle_id") Long vehicleId,@ApiParam(value = "Time in unix milliseconds that represents the oldest routes to return. Used in combination with duration. Defaults to now.") @Valid @RequestParam(value = "end_time", required = false) Long endTime,@ApiParam(value = "Time in milliseconds that represents the duration before end_time to query. Defaults to 24 hours.") @Valid @RequestParam(value = "duration", required = false) Long duration);


    @ApiOperation(value = "/fleet/drivers/{driver_id:[0-9]+ | external_id:[a-zA-Z0-9]+}", nickname = "getDriverById", notes = "Fetch driver by id.", response = CurrentDriver.class, tags={ "Fleet","Drivers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns the driver for the given driver_id.", response = CurrentDriver.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/{driver_id_or_external_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<CurrentDriver> getDriverById(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the driver.  This must be either the numeric ID generated by Samsara or the external ID of the driver.  External IDs are customer specified key-value pairs.",required=true) @PathVariable("driver_id_or_external_id") String driverIdOrExternalId);


    @ApiOperation(value = "/fleet/drivers/document_types", nickname = "getDriverDocumentTypesByOrgId", notes = "Fetch all of the document types.", response = DocumentTypes.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns all of the document types.", response = DocumentTypes.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/document_types",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<DocumentTypes> getDriverDocumentTypesByOrgId();


    @ApiOperation(value = "/fleet/drivers/documents", nickname = "getDriverDocumentsByOrgId", notes = "Fetch all of the documents.", response = Documents.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns all of the documents.", response = Documents.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/documents",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Documents> getDriverDocumentsByOrgId(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Time in unix milliseconds that represents the oldest documents to return. Used in combination with durationMs. Defaults to now.") @Valid @RequestParam(value = "endMs", required = false) Long endMs,@ApiParam(value = "Time in milliseconds that represents the duration before endMs to query. Defaults to 24 hours.") @Valid @RequestParam(value = "durationMs", required = false) Long durationMs);


    @ApiOperation(value = "/fleet/drivers/{driverId:[0-9]+}/safety/score", nickname = "getDriverSafetyScore", notes = "Fetch the safety score for the driver.", response = DriverSafetyScoreResponse.class, tags={ "Fleet","Safety", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Safety score details.", response = DriverSafetyScoreResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/{driverId}/safety/score",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<DriverSafetyScoreResponse> getDriverSafetyScore(@ApiParam(value = "ID of the driver",required=true) @PathVariable("driverId") Long driverId,@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@NotNull @ApiParam(value = "Timestamp in milliseconds representing the start of the period to fetch, inclusive. Used in combination with endMs.", required = true) @Valid @RequestParam(value = "startMs", required = true) Long startMs,@NotNull @ApiParam(value = "Timestamp in milliseconds representing the end of the period to fetch, inclusive. Used in combination with startMs.", required = true) @Valid @RequestParam(value = "endMs", required = true) Long endMs);


    @ApiOperation(value = "/fleet/maintenance/dvirs", nickname = "getDvirs", notes = "Get DVIRs for the org within provided time constraints", response = DvirListResponse.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "DVIRs for the specified duration.", response = DvirListResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/maintenance/dvirs",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<DvirListResponse> getDvirs(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@NotNull @ApiParam(value = "time in millis until the last dvir log.", required = true) @Valid @RequestParam(value = "end_ms", required = true) Integer endMs,@NotNull @ApiParam(value = "time in millis which corresponds to the duration before the end_ms.", required = true) @Valid @RequestParam(value = "duration_ms", required = true) Integer durationMs,@ApiParam(value = "Group ID to query.") @Valid @RequestParam(value = "group_id", required = false) Integer groupId);


    @ApiOperation(value = "/fleet/drivers", nickname = "getFleetDrivers", notes = "Get all the drivers for the specified group.", response = DriversResponse.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "All drivers in the group.", response = DriversResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<DriversResponse> getFleetDrivers(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "" ,required=true )  @Valid @RequestBody GroupDriversParam groupDriversParam);


    @ApiOperation(value = "/fleet/drivers/{driver_id:[0-9]+}/hos_daily_logs", nickname = "getFleetDriversHosDailyLogs", notes = "Get summarized daily HOS charts for a specified driver.", response = DriverDailyLogResponse.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Distance traveled and time active for each driver in the organization over the specified time period.", response = DriverDailyLogResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/{driver_id}/hos_daily_logs",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<DriverDailyLogResponse> getFleetDriversHosDailyLogs(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the driver with HOS logs.",required=true) @PathVariable("driver_id") Long driverId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody HosLogsParam hosLogsParam);


    @ApiOperation(value = "/fleet/drivers/summary", nickname = "getFleetDriversSummary", notes = "Get the distance and time each driver in an organization has driven in a given time period.", response = DriversSummaryResponse.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Distance traveled and time active for each driver in the organization over the specified time period.", response = DriversSummaryResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/summary",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<DriversSummaryResponse> getFleetDriversSummary(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Org ID and time range to query." ,required=true )  @Valid @RequestBody DriversSummaryParam driversSummaryParam,@ApiParam(value = "Snap query result to HOS day boundaries.") @Valid @RequestParam(value = "snap_to_day_bounds", required = false) Boolean snapToDayBounds);


    @ApiOperation(value = "/fleet/hos_authentication_logs", nickname = "getFleetHosAuthenticationLogs", notes = "Get the HOS (hours of service) signin and signout logs for the specified driver. Only signout logs include location information.", response = HosAuthenticationLogsResponse.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "HOS authentication logs for the specified driver.", response = HosAuthenticationLogsResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/hos_authentication_logs",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<HosAuthenticationLogsResponse> getFleetHosAuthenticationLogs(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "" ,required=true )  @Valid @RequestBody HosAuthenticationLogsParam hosAuthenticationLogsParam);


    @ApiOperation(value = "/fleet/hos_logs", nickname = "getFleetHosLogs", notes = "Get the HOS (hours of service) logs for the specified driver. This method returns all the HOS statuses that the driver was in during this time period.", response = HosLogsResponse.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "HOS logs for the specified driver.", response = HosLogsResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/hos_logs",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<HosLogsResponse> getFleetHosLogs(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "" ,required=true )  @Valid @RequestBody HosLogsParam1 hosLogsParam);


    @ApiOperation(value = "/fleet/hos_logs_summary", nickname = "getFleetHosLogsSummary", notes = "Get the current HOS status for all drivers in the group.", response = HosLogsSummaryResponse.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "HOS logs for the specified driver.", response = HosLogsSummaryResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/hos_logs_summary",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<HosLogsSummaryResponse> getFleetHosLogsSummary(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "" ,required=true )  @Valid @RequestBody HosLogsParam2 hosLogsParam);


    @ApiOperation(value = "/fleet/locations", nickname = "getFleetLocations", notes = "Get current location of vehicles in a group. This method returns the current location in latitude and longitude of all vehicles in a requested group.", response = InlineResponse2003.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of vehicle objects containing their location and the time at which that location was logged.", response = InlineResponse2003.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/locations",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<InlineResponse2003> getFleetLocations(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Group ID to query." ,required=true )  @Valid @RequestBody GroupParam groupParam);


    @ApiOperation(value = "/fleet/maintenance/list", nickname = "getFleetMaintenanceList", notes = "Get list of the vehicles with any engine faults or check light data.", response = InlineResponse2004.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of vehicles and maintenance information about each.", response = InlineResponse2004.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/maintenance/list",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<InlineResponse2004> getFleetMaintenanceList(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Group ID to query." ,required=true )  @Valid @RequestBody GroupParam groupParam);


    @ApiOperation(value = "/fleet/trips", nickname = "getFleetTrips", notes = "Get historical trips data for specified vehicle. This method returns a set of historical trips data for the specified vehicle in the specified time range.", response = TripResponse.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of trips taken by the requested vehicle within the specified timeframe.", response = TripResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/trips",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<TripResponse> getFleetTrips(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Group ID, vehicle ID and time range to query." ,required=true )  @Valid @RequestBody TripsParam tripsParam);


    @ApiOperation(value = "/fleet/vehicles/{vehicle_id:[0-9]+ | external_id:[a-zA-Z0-9]+}", nickname = "getFleetVehicle", notes = "Gets a specific vehicle.", response = FleetVehicleResponse.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The specified vehicle.", response = FleetVehicleResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/vehicles/{vehicle_id_or_external_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<FleetVehicleResponse> getFleetVehicle(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the vehicle.  This must be either the numeric ID generated by Samsara or the external ID of the vehicle.  External IDs are customer specified key-value pairs.",required=true) @PathVariable("vehicle_id_or_external_id") String vehicleIdOrExternalId);


    @ApiOperation(value = "/fleet/vehicles/{vehicleId:[0-9]+}/safety/harsh_event", nickname = "getVehicleHarshEvent", notes = "Fetch harsh event details for a vehicle.", response = VehicleHarshEventResponse.class, tags={ "Fleet","Safety", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Harsh event details.", response = VehicleHarshEventResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/vehicles/{vehicleId}/safety/harsh_event",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<VehicleHarshEventResponse> getVehicleHarshEvent(@ApiParam(value = "ID of the vehicle",required=true) @PathVariable("vehicleId") Long vehicleId,@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@NotNull @ApiParam(value = "Timestamp in milliseconds representing the timestamp of a harsh event.", required = true) @Valid @RequestParam(value = "timestamp", required = true) Long timestamp);


    @ApiOperation(value = "/fleet/vehicles/{vehicle_id:[0-9]+}/locations", nickname = "getVehicleLocations", notes = "Fetch locations for a given vehicle between a start/end time. The maximum query duration is one hour.", response = FleetVehicleLocations.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns locations for a given vehicle between a start/end time, with a maximum query duration of one hour.", response = FleetVehicleLocations.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/vehicles/{vehicle_id}/locations",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<FleetVehicleLocations> getVehicleLocations(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the vehicle with the associated routes.",required=true) @PathVariable("vehicle_id") Long vehicleId,@NotNull @ApiParam(value = "Time in Unix epoch milliseconds for the start of the query (cannot exceed 1 hour)", required = true) @Valid @RequestParam(value = "startMs", required = true) Long startMs,@NotNull @ApiParam(value = "Time in Unix epoch milliseconds for the end of the query (cannot exceed 1 hour)", required = true) @Valid @RequestParam(value = "endMs", required = true) Long endMs);


    @ApiOperation(value = "/fleet/vehicles/{vehicleId:[0-9]+}/safety/score", nickname = "getVehicleSafetyScore", notes = "Fetch the safety score for the vehicle.", response = VehicleSafetyScoreResponse.class, tags={ "Fleet","Safety", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Safety score details.", response = VehicleSafetyScoreResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/vehicles/{vehicleId}/safety/score",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<VehicleSafetyScoreResponse> getVehicleSafetyScore(@ApiParam(value = "ID of the vehicle",required=true) @PathVariable("vehicleId") Long vehicleId,@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@NotNull @ApiParam(value = "Timestamp in milliseconds representing the start of the period to fetch, inclusive. Used in combination with endMs.", required = true) @Valid @RequestParam(value = "startMs", required = true) Long startMs,@NotNull @ApiParam(value = "Timestamp in milliseconds representing the end of the period to fetch, inclusive. Used in combination with startMs.", required = true) @Valid @RequestParam(value = "endMs", required = true) Long endMs);


    @ApiOperation(value = "/fleet/vehicles/stats", nickname = "getVehicleStats", notes = "Fetch engine state and aux input data for all vehicles in the group between a start/end time. Data returned may be affected by device connectivity and processing time.", response = InlineResponse2005.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns engine state and/or aux input data for all vehicles in the group between a start/end time.", response = InlineResponse2005.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/vehicles/stats",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<InlineResponse2005> getVehicleStats(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@NotNull @ApiParam(value = "Time in Unix epoch milliseconds for the start of the query.", required = true) @Valid @RequestParam(value = "startMs", required = true) Integer startMs,@NotNull @ApiParam(value = "Time in Unix epoch milliseconds for the end of the query.", required = true) @Valid @RequestParam(value = "endMs", required = true) Integer endMs,@ApiParam(value = "Comma-separated list of stat types. Options are engineState, auxInput1, and auxInput2. If this parameter is excluded, all 3 stat types will be returned. Example: series=engineState,auxInput2", allowableValues = "engineState, auxInput1, auxInput2") @Valid @RequestParam(value = "series", required = false) String series,@ApiParam(value = "Comma-separated list of tag ids. Example: tagIds=1,2,3") @Valid @RequestParam(value = "tagIds", required = false) String tagIds,@ApiParam(value = "Pagination parameter indicating the cursor position to continue returning results after. Used in conjunction with the 'limit' parameter. Mutually exclusive with 'endingBefore' parameter.") @Valid @RequestParam(value = "startingAfter", required = false) String startingAfter,@ApiParam(value = "Pagination parameter indicating the cursor position to return results before. Used in conjunction with the 'limit' parameter. Mutually exclusive with 'startingAfter' parameter.") @Valid @RequestParam(value = "endingBefore", required = false) String endingBefore,@ApiParam(value = "Pagination parameter indicating the number of results to return in this request. Used in conjunction with either 'startingAfter' or 'endingBefore'.") @Valid @RequestParam(value = "limit", required = false) Long limit);


    @ApiOperation(value = "/fleet/vehicles/locations", nickname = "getVehiclesLocations", notes = "Fetch locations for a given vehicle between a start/end time. The maximum query duration is 30 minutes.", response = FleetVehiclesLocations.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns locations for a given vehicle between a start/end time, with a maximum query duration of 30 minutes.", response = FleetVehiclesLocations.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/vehicles/locations",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<FleetVehiclesLocations> getVehiclesLocations(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@NotNull @ApiParam(value = "Time in Unix epoch milliseconds for the start of the query (cannot exceed 30 minutes)", required = true) @Valid @RequestParam(value = "startMs", required = true) Integer startMs,@NotNull @ApiParam(value = "Time in Unix epoch milliseconds for the end of the query (cannot exceed 30 minutes)", required = true) @Valid @RequestParam(value = "endMs", required = true) Integer endMs);


    @ApiOperation(value = "/fleet/list", nickname = "listFleet", notes = "Get list of the vehicles. This method returns a list of the vehicles in the Samsara Cloud and information about them.", response = InlineResponse2002.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of vehicles and information about each.", response = InlineResponse2002.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/list",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<InlineResponse2002> listFleet(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "Group ID to query." ,required=true )  @Valid @RequestBody GroupParam groupParam,@ApiParam(value = "Pagination parameter indicating the cursor position to continue returning results after. Used in conjunction with the 'limit' parameter. Mutually exclusive with 'endingBefore' parameter.") @Valid @RequestParam(value = "startingAfter", required = false) String startingAfter,@ApiParam(value = "Pagination parameter indicating the cursor position to return results before. Used in conjunction with the 'limit' parameter. Mutually exclusive with 'startingAfter' parameter.") @Valid @RequestParam(value = "endingBefore", required = false) String endingBefore,@ApiParam(value = "Pagination parameter indicating the number of results to return in this request. Used in conjunction with either 'startingAfter' or 'endingBefore'.") @Valid @RequestParam(value = "limit", required = false) Long limit);


    @ApiOperation(value = "/fleet/vehicles/{vehicle_id:[0-9]+ | external_id:[a-zA-Z0-9]+}", nickname = "patchFleetVehicle", notes = "Updates the specified vehicle using JSON merge patch format. See IETF RFC 7396: https://tools.ietf.org/html/rfc7396.", response = FleetVehicleResponse.class, tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The updated vehicle.", response = FleetVehicleResponse.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/vehicles/{vehicle_id_or_external_id}",
        produces = { "application/json" }, 
        consumes = { "application/json", "application/merge-patch+json" },
        method = RequestMethod.PATCH)
    ResponseEntity<FleetVehicleResponse> patchFleetVehicle(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the vehicle.  This must be either the numeric ID generated by Samsara or the external ID of the vehicle.  External IDs are customer specified key-value pairs.",required=true) @PathVariable("vehicle_id_or_external_id") String vehicleIdOrExternalId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Data data);


    @ApiOperation(value = "/fleet/drivers/inactive/{driver_id:[0-9]+ | external_id:[a-zA-Z0-9]+}", nickname = "reactivateDriverById", notes = "Reactivate the inactive driver having id.", response = CurrentDriver.class, tags={ "Fleet","Drivers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns the reactivated driver, which is now available at /fleet/drivers/{driver_id}.", response = CurrentDriver.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/drivers/inactive/{driver_id_or_external_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<CurrentDriver> reactivateDriverById(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the driver.  This must be either the numeric ID generated by Samsara or the external ID of the driver.  External IDs are customer specified key-value pairs.",required=true) @PathVariable("driver_id_or_external_id") String driverIdOrExternalId,@ApiParam(value = "Driver reactivation body" ,required=true )  @Valid @RequestBody ReactivateDriverParam reactivateDriverParam);


    @ApiOperation(value = "/fleet/dispatch/routes/{route_id:[0-9]+}/", nickname = "updateDispatchRouteById", notes = "Update a dispatch route and its associated jobs.", response = DispatchRoute.class, tags={ "Fleet","Routes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Update the dispatch route. Allowable updates include setting job state, adding or removing jobs, and changing job locations and times.", response = DispatchRoute.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/dispatch/routes/{route_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<DispatchRoute> updateDispatchRouteById(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "ID of the dispatch route.",required=true) @PathVariable("route_id") Long routeId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody DispatchRoute updateDispatchRouteParams);


    @ApiOperation(value = "/fleet/set_data", nickname = "updateVehicles", notes = "This method enables the mutation of metadata for vehicles in the Samsara Cloud.", tags={ "Fleet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Vehicles were successfully updated. No response body is returned."),
        @ApiResponse(code = 200, message = "Unexpected error.", response = String.class) })
    @RequestMapping(value = "/fleet/set_data",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> updateVehicles(@NotNull @ApiParam(value = "Samsara API access token.", required = true) @Valid @RequestParam(value = "access_token", required = true) String accessToken,@ApiParam(value = "" ,required=true )  @Valid @RequestBody VehicleUpdateParam vehicleUpdateParam);

}
