<?php
/*
 * SamsaraAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SamsaraAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Sensor5 implements JsonSerializable
{
    /**
     * Flag indicating whether the current cargo is empty or loaded.
     * @var bool|null $cargoEmpty public property
     */
    public $cargoEmpty;

    /**
     * ID of the sensor.
     * @var integer|null $id public property
     */
    public $id;

    /**
     * Name of the sensor.
     * @var string|null $name public property
     */
    public $name;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool    $cargoEmpty Initialization value for $this->cargoEmpty
     * @param integer $id         Initialization value for $this->id
     * @param string  $name       Initialization value for $this->name
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->cargoEmpty = func_get_arg(0);
            $this->id         = func_get_arg(1);
            $this->name       = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['cargoEmpty'] = $this->cargoEmpty;
        $json['id']         = $this->id;
        $json['name']       = $this->name;

        return $json;
    }
}
