//
// AssetCable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AssetCable: Codable {

    /** Asset type */
    public var assetType: String?

    public init(assetType: String?) {
        self.assetType = assetType
    }


}

