//
// InlineResponse2009.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2009: Codable {

    public var tags: [Tag]?

    public init(tags: [Tag]?) {
        self.tags = tags
    }


}

