export * from './assetsApi';
import { AssetsApi } from './assetsApi';
export * from './driversApi';
import { DriversApi } from './driversApi';
export * from './fleetApi';
import { FleetApi } from './fleetApi';
export * from './industrialApi';
import { IndustrialApi } from './industrialApi';
export * from './routesApi';
import { RoutesApi } from './routesApi';
export * from './safetyApi';
import { SafetyApi } from './safetyApi';
export * from './sensorsApi';
import { SensorsApi } from './sensorsApi';
export * from './tagsApi';
import { TagsApi } from './tagsApi';
export * from './usersApi';
import { UsersApi } from './usersApi';
export const APIS = [AssetsApi, DriversApi, FleetApi, IndustrialApi, RoutesApi, SafetyApi, SensorsApi, TagsApi, UsersApi];
