<?php
/**
 * InlineObject22
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * InlineObject22
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InlineObject22
{
    
    /** @var int $groupId Group ID to query.*/
    private $groupId;
    
    /** @var int[] $sensors List of sensor IDs to query.*/
    private $sensors;
}
