<?php
/**
 * MachineHistoryResponseVibrations
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * MachineHistoryResponseVibrations
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class MachineHistoryResponseVibrations
{
    
    /** @var double $x */
    private $x;
    
    /** @var double $y */
    private $y;
    
    /** @var double $z */
    private $z;
    
    /** @var int $time */
    private $time;
}
