<?php
/**
 * TagModify
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * TagModify
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TagModify
{
    
    /** @var \OpenAPIServer\Model\TagModifyAdd $add */
    private $add;
    
    /** @var \OpenAPIServer\Model\TagModifyDelete $delete */
    private $delete;
    
    /** @var string $name Updated name of this tag.*/
    private $name;
    
    /** @var int $parentTagId If this tag is part a hierarchical tag tree as a child tag, the parentTagId is the ID of this tag&#39;s parent tag.*/
    private $parentTagId;
}
