# -*- coding: utf-8 -*-

"""
    samsaraapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import samsaraapi.models.alarm_1

class Alarm(object):

    """Implementation of the 'Alarm' model.

    TODO: type model description here.

    Attributes:
        alarms (list of Alarm1): TODO: type description here.
        changed_at_ms (long|int): Timestamp when the alarms were reported, in
            Unix milliseconds since epoch

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "alarms":'alarms',
        "changed_at_ms":'changedAtMs'
    }

    def __init__(self,
                 alarms=None,
                 changed_at_ms=None):
        """Constructor for the Alarm class"""

        # Initialize members of the class
        self.alarms = alarms
        self.changed_at_ms = changed_at_ms


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        alarms = None
        if dictionary.get('alarms') != None:
            alarms = list()
            for structure in dictionary.get('alarms'):
                alarms.append(samsaraapi.models.alarm_1.Alarm1.from_dictionary(structure))
        changed_at_ms = dictionary.get('changedAtMs')

        # Return an object of this model
        return cls(alarms,
                   changed_at_ms)


