# -*- coding: utf-8 -*-

"""
    samsaraapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import samsaraapi.models.cable
import samsaraapi.models.asset_current_location

class AssetCurrentLocationsResponse(object):

    """Implementation of the 'AssetCurrentLocationsResponse' model.

    Basic information of an asset

    Attributes:
        cable (list of Cable): The cable connected to the asset
        engine_hours (int): Engine hours
        id (long|int): Asset ID
        location (list of AssetCurrentLocation): Current location of an asset
        name (string): Asset name

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id":'id',
        "cable":'cable',
        "engine_hours":'engineHours',
        "location":'location',
        "name":'name'
    }

    def __init__(self,
                 id=None,
                 cable=None,
                 engine_hours=None,
                 location=None,
                 name=None):
        """Constructor for the AssetCurrentLocationsResponse class"""

        # Initialize members of the class
        self.cable = cable
        self.engine_hours = engine_hours
        self.id = id
        self.location = location
        self.name = name


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        cable = None
        if dictionary.get('cable') != None:
            cable = list()
            for structure in dictionary.get('cable'):
                cable.append(samsaraapi.models.cable.Cable.from_dictionary(structure))
        engine_hours = dictionary.get('engineHours')
        location = None
        if dictionary.get('location') != None:
            location = list()
            for structure in dictionary.get('location'):
                location.append(samsaraapi.models.asset_current_location.AssetCurrentLocation.from_dictionary(structure))
        name = dictionary.get('name')

        # Return an object of this model
        return cls(id,
                   cable,
                   engine_hours,
                   location,
                   name)


