# -*- coding: utf-8 -*-

"""
    samsaraapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import samsaraapi.models.series_1

class HistoryParam1(object):

    """Implementation of the 'historyParam1' model.

    TODO: type model description here.

    Attributes:
        end_ms (long|int): End of the time range, specified in milliseconds
            UNIX time.
        fill_missing (FillMissingEnum): TODO: type description here.
        group_id (long|int): Group ID to query.
        series (list of Series1): TODO: type description here.
        start_ms (long|int): Beginning of the time range, specified in
            milliseconds UNIX time.
        step_ms (int): Time resolution for which data should be returned, in
            milliseconds. Specifying 3600000 will return data at hour
            intervals.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "end_ms":'endMs',
        "group_id":'groupId',
        "series":'series',
        "start_ms":'startMs',
        "step_ms":'stepMs',
        "fill_missing":'fillMissing'
    }

    def __init__(self,
                 end_ms=None,
                 group_id=None,
                 series=None,
                 start_ms=None,
                 step_ms=None,
                 fill_missing='withNull'):
        """Constructor for the HistoryParam1 class"""

        # Initialize members of the class
        self.end_ms = end_ms
        self.fill_missing = fill_missing
        self.group_id = group_id
        self.series = series
        self.start_ms = start_ms
        self.step_ms = step_ms


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        end_ms = dictionary.get('endMs')
        group_id = dictionary.get('groupId')
        series = None
        if dictionary.get('series') != None:
            series = list()
            for structure in dictionary.get('series'):
                series.append(samsaraapi.models.series_1.Series1.from_dictionary(structure))
        start_ms = dictionary.get('startMs')
        step_ms = dictionary.get('stepMs')
        fill_missing = dictionary.get("fillMissing") if dictionary.get("fillMissing") else 'withNull'

        # Return an object of this model
        return cls(end_ms,
                   group_id,
                   series,
                   start_ms,
                   step_ms,
                   fill_missing)


