# -*- coding: utf-8 -*-

"""
    samsaraapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ReturnAirTemp(object):

    """Implementation of the 'ReturnAirTemp' model.

    TODO: type model description here.

    Attributes:
        changed_at_ms (long|int): Timestamp in Unix milliseconds since epoch.
        temp_in_milli_c (long|int): Return air temperature in millidegree
            Celsius.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "changed_at_ms":'changedAtMs',
        "temp_in_milli_c":'tempInMilliC'
    }

    def __init__(self,
                 changed_at_ms=None,
                 temp_in_milli_c=None):
        """Constructor for the ReturnAirTemp class"""

        # Initialize members of the class
        self.changed_at_ms = changed_at_ms
        self.temp_in_milli_c = temp_in_milli_c


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        changed_at_ms = dictionary.get('changedAtMs')
        temp_in_milli_c = dictionary.get('tempInMilliC')

        # Return an object of this model
        return cls(changed_at_ms,
                   temp_in_milli_c)


