package org.openapitools.server.api.verticle;

import org.openapitools.server.api.model.Address;
import org.openapitools.server.api.model.AllRouteJobUpdates;
import org.openapitools.server.api.model.AssetReeferResponse;
import org.openapitools.server.api.model.Contact;
import org.openapitools.server.api.model.DispatchRoute;
import org.openapitools.server.api.model.DispatchRouteCreate;
import org.openapitools.server.api.model.DispatchRouteHistory;
import org.openapitools.server.api.model.Document;
import org.openapitools.server.api.model.DocumentCreate;
import org.openapitools.server.api.model.DocumentType;
import org.openapitools.server.api.model.Driver;
import org.openapitools.server.api.model.DriverDailyLogResponse;
import org.openapitools.server.api.model.DriverForCreate;
import org.openapitools.server.api.model.DriverSafetyScoreResponse;
import org.openapitools.server.api.model.DriversResponse;
import org.openapitools.server.api.model.DriversSummaryResponse;
import org.openapitools.server.api.model.DvirBase;
import org.openapitools.server.api.model.DvirListResponse;
import org.openapitools.server.api.model.FleetVehicleLocation;
import org.openapitools.server.api.model.FleetVehicleResponse;
import org.openapitools.server.api.model.HosAuthenticationLogsResponse;
import org.openapitools.server.api.model.HosLogsResponse;
import org.openapitools.server.api.model.HosLogsSummaryResponse;
import org.openapitools.server.api.model.InlineObject;
import org.openapitools.server.api.model.InlineObject1;
import org.openapitools.server.api.model.InlineObject10;
import org.openapitools.server.api.model.InlineObject11;
import org.openapitools.server.api.model.InlineObject12;
import org.openapitools.server.api.model.InlineObject13;
import org.openapitools.server.api.model.InlineObject14;
import org.openapitools.server.api.model.InlineObject15;
import org.openapitools.server.api.model.InlineObject16;
import org.openapitools.server.api.model.InlineObject2;
import org.openapitools.server.api.model.InlineObject3;
import org.openapitools.server.api.model.InlineObject4;
import org.openapitools.server.api.model.InlineObject5;
import org.openapitools.server.api.model.InlineObject6;
import org.openapitools.server.api.model.InlineObject7;
import org.openapitools.server.api.model.InlineObject8;
import org.openapitools.server.api.model.InlineObject9;
import org.openapitools.server.api.model.InlineResponse200;
import org.openapitools.server.api.model.InlineResponse2001;
import org.openapitools.server.api.model.InlineResponse2002;
import org.openapitools.server.api.model.InlineResponse2003;
import org.openapitools.server.api.model.InlineResponse2004;
import org.openapitools.server.api.model.InlineResponse2005;
import org.openapitools.server.api.MainApiException;
import org.openapitools.server.api.model.TripResponse;
import org.openapitools.server.api.model.VehicleHarshEventResponse;
import org.openapitools.server.api.model.VehicleSafetyScoreResponse;

public final class FleetApiException extends MainApiException {
    public FleetApiException(int statusCode, String statusMessage) {
        super(statusCode, statusMessage);
    }
    
    public static final FleetApiException Fleet_addFleetAddress_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_addOrganizationAddresses_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_createDispatchRoute_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_createDriver_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_createDriverDispatchRoute_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_createDriverDocument_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_createDvir_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_createVehicleDispatchRoute_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_deactivateDriver_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_deleteDispatchRouteById_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_deleteOrganizationAddress_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_fetchAllDispatchRoutes_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_fetchAllRouteJobUpdates_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getAllAssetCurrentLocations_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getAllAssets_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getAllDeactivatedDrivers_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getAssetLocation_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getAssetReefer_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getDeactivatedDriverById_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getDispatchRouteById_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getDispatchRouteHistory_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getDispatchRoutesByDriverId_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getDispatchRoutesByVehicleId_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getDriverById_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getDriverDocumentTypesByOrgId_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getDriverDocumentsByOrgId_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getDriverSafetyScore_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getDvirs_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getFleetDrivers_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getFleetDriversHosDailyLogs_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getFleetDriversSummary_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getFleetHosAuthenticationLogs_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getFleetHosLogs_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getFleetHosLogsSummary_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getFleetLocations_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getFleetMaintenanceList_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getFleetTrips_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getFleetVehicle_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getOrganizationAddress_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getOrganizationAddresses_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getOrganizationContact_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getVehicleHarshEvent_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getVehicleLocations_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getVehicleSafetyScore_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getVehicleStats_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_getVehiclesLocations_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_listContacts_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_listFleet_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_patchFleetVehicle_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_reactivateDriverById_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_updateDispatchRouteById_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_updateOrganizationAddress_0_Exception = new FleetApiException(0, "Unexpected error.");
    public static final FleetApiException Fleet_updateVehicles_0_Exception = new FleetApiException(0, "Unexpected error.");
    

}