//
// InlineObject4.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineObject4: Codable {

    /** True indicates that this driver should be reactivated. */
    public var reactivate: Bool

    public init(reactivate: Bool) {
        self.reactivate = reactivate
    }


}

