//
// InlineResponse2007.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2007: Codable {

    public var machines: [Machine]?

    public init(machines: [Machine]?) {
        self.machines = machines
    }


}

