//
// InlineResponse2008.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2008: Codable {

    public var sensors: [Sensor]?

    public init(sensors: [Sensor]?) {
        self.sensors = sensors
    }


}

