# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SamsaraAPI.Model.AddressesAddresses do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"notes",
    :"formattedAddress",
    :"geofence",
    :"tagIds",
    :"name",
    :"contactIds"
  ]

  @type t :: %__MODULE__{
    :"notes" => String.t | nil,
    :"formattedAddress" => String.t,
    :"geofence" => AddressGeofence,
    :"tagIds" => [integer()] | nil,
    :"name" => String.t,
    :"contactIds" => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: SamsaraAPI.Model.AddressesAddresses do
  import SamsaraAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"geofence", :struct, SamsaraAPI.Model.AddressGeofence, options)
  end
end

