# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SamsaraAPI.Model.AddressGeofencePolygon do
  @moduledoc """
  Information about a polygon geofence. This field is only populated if the geofence is a polygon.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"vertices"
  ]

  @type t :: %__MODULE__{
    :"vertices" => [AddressGeofencePolygonVertices] | nil
  }
end

defimpl Poison.Decoder, for: SamsaraAPI.Model.AddressGeofencePolygon do
  import SamsaraAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"vertices", :list, SamsaraAPI.Model.AddressGeofencePolygonVertices, options)
  end
end

