# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SamsaraAPI.Model.DoorResponseSensors do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"doorClosed",
    :"name",
    :"id"
  ]

  @type t :: %__MODULE__{
    :"doorClosed" => boolean() | nil,
    :"name" => String.t | nil,
    :"id" => integer() | nil
  }
end

defimpl Poison.Decoder, for: SamsaraAPI.Model.DoorResponseSensors do
  def decode(value, _options) do
    value
  end
end

