# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SamsaraAPI.Model.DriversSummaryResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Summaries"
  ]

  @type t :: %__MODULE__{
    :"Summaries" => [DriversSummaryResponseSummaries] | nil
  }
end

defimpl Poison.Decoder, for: SamsaraAPI.Model.DriversSummaryResponse do
  import SamsaraAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Summaries", :list, SamsaraAPI.Model.DriversSummaryResponseSummaries, options)
  end
end

