# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SamsaraAPI.Model.Tag do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"addresses",
    :"assets",
    :"drivers",
    :"groupId",
    :"id",
    :"machines",
    :"name",
    :"parentTagId",
    :"sensors",
    :"vehicles"
  ]

  @type t :: %__MODULE__{
    :"addresses" => [TaggedAddress] | nil,
    :"assets" => [TaggedAsset] | nil,
    :"drivers" => [TaggedDriver] | nil,
    :"groupId" => integer() | nil,
    :"id" => integer(),
    :"machines" => [TaggedMachine] | nil,
    :"name" => String.t,
    :"parentTagId" => integer() | nil,
    :"sensors" => [TaggedSensor] | nil,
    :"vehicles" => [TaggedVehicle] | nil
  }
end

defimpl Poison.Decoder, for: SamsaraAPI.Model.Tag do
  import SamsaraAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"addresses", :list, SamsaraAPI.Model.TaggedAddress, options)
    |> deserialize(:"assets", :list, SamsaraAPI.Model.TaggedAsset, options)
    |> deserialize(:"drivers", :list, SamsaraAPI.Model.TaggedDriver, options)
    |> deserialize(:"machines", :list, SamsaraAPI.Model.TaggedMachine, options)
    |> deserialize(:"sensors", :list, SamsaraAPI.Model.TaggedSensor, options)
    |> deserialize(:"vehicles", :list, SamsaraAPI.Model.TaggedVehicle, options)
  end
end

