# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SamsaraAPI.Model.TaggedDriverBase do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id"
  ]

  @type t :: %__MODULE__{
    :"id" => integer()
  }
end

defimpl Poison.Decoder, for: SamsaraAPI.Model.TaggedDriverBase do
  def decode(value, _options) do
    value
  end
end

