# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule SamsaraAPI.Model.TemperatureResponse do
  @moduledoc """
  Contains the current temperatures of a sensor.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"groupId",
    :"sensors"
  ]

  @type t :: %__MODULE__{
    :"groupId" => integer() | nil,
    :"sensors" => [TemperatureResponseSensors] | nil
  }
end

defimpl Poison.Decoder, for: SamsaraAPI.Model.TemperatureResponse do
  import SamsaraAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sensors", :list, SamsaraAPI.Model.TemperatureResponseSensors, options)
  end
end

