export * from './AssetsApi';
import { AssetsApi } from './AssetsApi';
export * from './DriversApi';
import { DriversApi } from './DriversApi';
export * from './FleetApi';
import { FleetApi } from './FleetApi';
export * from './IndustrialApi';
import { IndustrialApi } from './IndustrialApi';
export * from './RoutesApi';
import { RoutesApi } from './RoutesApi';
export * from './SafetyApi';
import { SafetyApi } from './SafetyApi';
export * from './SensorsApi';
import { SensorsApi } from './SensorsApi';
export * from './TagsApi';
import { TagsApi } from './TagsApi';
export * from './UsersApi';
import { UsersApi } from './UsersApi';
export const APIS = [AssetsApi, DriversApi, FleetApi, IndustrialApi, RoutesApi, SafetyApi, SensorsApi, TagsApi, UsersApi];
