/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a BodyModel.
 */
class BodyModel {
  /**
   * Create a BodyModel.
   * @property {number} groupId Group ID to query.
   */
  constructor() {
  }

  /**
   * Defines the metadata of BodyModel
   *
   * @returns {object} metadata of BodyModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'body',
      type: {
        name: 'Composite',
        className: 'BodyModel',
        modelProperties: {
          groupId: {
            required: true,
            serializedName: 'groupId',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = BodyModel;
