/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a HumidityResponseSensorsItem.
 */
class HumidityResponseSensorsItem {
  /**
   * Create a HumidityResponseSensorsItem.
   * @property {number} [humidity] Currently reported relative humidity in
   * percent, from 0-100.
   * @property {number} [id] ID of the sensor.
   * @property {string} [name] Name of the sensor.
   */
  constructor() {
  }

  /**
   * Defines the metadata of HumidityResponseSensorsItem
   *
   * @returns {object} metadata of HumidityResponseSensorsItem
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'HumidityResponse_sensorsItem',
      type: {
        name: 'Composite',
        className: 'HumidityResponseSensorsItem',
        modelProperties: {
          humidity: {
            required: false,
            serializedName: 'humidity',
            type: {
              name: 'Number'
            }
          },
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'Number'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = HumidityResponseSensorsItem;
