/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Contains information about a sensor.
 *
 */
class Sensor {
  /**
   * Create a Sensor.
   * @property {number} id ID of the sensor.
   * @property {string} [macAddress] MAC address of the sensor.
   * @property {string} [name] Name of the sensor.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Sensor
   *
   * @returns {object} metadata of Sensor
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Sensor',
      type: {
        name: 'Composite',
        className: 'Sensor',
        modelProperties: {
          id: {
            required: true,
            serializedName: 'id',
            type: {
              name: 'Number'
            }
          },
          macAddress: {
            required: false,
            serializedName: 'macAddress',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Sensor;
