/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a TripsParam.
 */
class TripsParam {
  /**
   * Create a TripsParam.
   * @property {number} endMs End of the time range, specified in milliseconds
   * UNIX time.
   * @property {number} groupId Group ID to query.
   * @property {number} startMs Beginning of the time range, specified in
   * milliseconds UNIX time. Limited to a 90 day window with respect to startMs
   * and endMs
   * @property {number} vehicleId Vehicle ID to query.
   */
  constructor() {
  }

  /**
   * Defines the metadata of TripsParam
   *
   * @returns {object} metadata of TripsParam
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'tripsParam',
      type: {
        name: 'Composite',
        className: 'TripsParam',
        modelProperties: {
          endMs: {
            required: true,
            serializedName: 'endMs',
            type: {
              name: 'Number'
            }
          },
          groupId: {
            required: true,
            serializedName: 'groupId',
            type: {
              name: 'Number'
            }
          },
          startMs: {
            required: true,
            serializedName: 'startMs',
            type: {
              name: 'Number'
            }
          },
          vehicleId: {
            required: true,
            serializedName: 'vehicleId',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = TripsParam;
