# This file is auto-generated by OpenAPI Generator (https://openapi-generator.tech)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'Org.OpenAPITools RoutesApi' {
    Context 'RoutesApi' {
        It 'Invoke-RoutesApiCreateDispatchRoute' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -createDispatchRouteParams "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'RoutesApi' {
        It 'Invoke-RoutesApiCreateDriverDispatchRoute' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -driverId "TEST_VALUE" -createDispatchRouteParams "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'RoutesApi' {
        It 'Invoke-RoutesApiCreateVehicleDispatchRoute' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -vehicleId "TEST_VALUE" -createDispatchRouteParams "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'RoutesApi' {
        It 'Invoke-RoutesApiDeleteDispatchRouteById' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -routeId "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'RoutesApi' {
        It 'Invoke-RoutesApiFetchAllDispatchRoutes' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -groupId "TEST_VALUE" -endTime "TEST_VALUE" -duration "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'RoutesApi' {
        It 'Invoke-RoutesApiFetchAllRouteJobUpdates' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -groupId "TEST_VALUE" -sequenceId "TEST_VALUE" -include "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'RoutesApi' {
        It 'Invoke-RoutesApiGetDispatchRouteById' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -routeId "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'RoutesApi' {
        It 'Invoke-RoutesApiGetDispatchRouteHistory' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -routeId "TEST_VALUE" -startTime "TEST_VALUE" -endTime "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'RoutesApi' {
        It 'Invoke-RoutesApiGetDispatchRoutesByDriverId' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -driverId "TEST_VALUE" -endTime "TEST_VALUE" -duration "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'RoutesApi' {
        It 'Invoke-RoutesApiGetDispatchRoutesByVehicleId' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -vehicleId "TEST_VALUE" -endTime "TEST_VALUE" -duration "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'RoutesApi' {
        It 'Invoke-RoutesApiUpdateDispatchRouteById' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -routeId "TEST_VALUE" -updateDispatchRouteParams "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
