# This file is auto-generated by OpenAPI Generator (https://openapi-generator.tech)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'Org.OpenAPITools UsersApi' {
    Context 'UsersApi' {
        It 'Invoke-UsersApiDeleteUserById' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -userId "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiGetUserById' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE" -userId "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiListUserRoles' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'UsersApi' {
        It 'Invoke-UsersApiListUsers' {
            $ret = Invoke-PetApiGetPetById -accessToken "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
