//
// DvirBaseNextDriverSignature.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** The next driver signature for the DVIR. */
public class DvirBaseNextDriverSignature: JSONEncodable {
    /** ID of the driver who signed the DVIR */
    public var driverId: Int64?
    /** The name of the driver who signed the next DVIR on this vehicle. */
    public var name: String?
    /** The time in millis when the next driver signed the DVIR on this vehicle. */
    public var signedAt: Int64?
    /** Type corresponds to driver. */
    public var type: String?
    /** Email of the  driver who signed the next DVIR on this vehicle. */
    public var email: String?
    /** Username of the  driver who signed the next DVIR on this vehicle. */
    public var username: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["driverId"] = self.driverId?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["signedAt"] = self.signedAt?.encodeToJSON()
        nillableDictionary["type"] = self.type
        nillableDictionary["email"] = self.email
        nillableDictionary["username"] = self.username
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
