//
// SensorHistoryResponseResults.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public class SensorHistoryResponseResults: JSONEncodable {
    /** List of datapoints, one for each requested (sensor, field) pair. */
    public var series: [Int64]?
    /** Timestamp in UNIX milliseconds. */
    public var timeMs: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["series"] = self.series?.encodeToJSON()
        nillableDictionary["timeMs"] = self.timeMs?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
