# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DocumentBase(Model):
    """DocumentBase.

    :param dispatch_job_id: ID of the Samsara dispatch job for which the
     document is submitted
    :type dispatch_job_id: long
    :param notes: Notes submitted with this document.
    :type notes: str
    """

    _attribute_map = {
        'dispatch_job_id': {'key': 'dispatchJobId', 'type': 'long'},
        'notes': {'key': 'notes', 'type': 'str'},
    }

    def __init__(self, dispatch_job_id=None, notes=None):
        super(DocumentBase, self).__init__()
        self.dispatch_job_id = dispatch_job_id
        self.notes = notes
