# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DocumentFieldCreate(Model):
    """DocumentFieldCreate.

    :param number_value: Value of this field if this document field has
     valueType: ValueType_Number.
    :type number_value: float
    :param photo_value: Value of this field if this document field has
     valueType: ValueType_Photo. Array of photo objects where each object
     contains a URL for a photo.
    :type photo_value: list[~swagger.models.DocumentFieldCreatePhotoValueItem]
    :param string_value: Value of this field if this document field has
     valueType: ValueType_String.
    :type string_value: str
    :param value_type: Determines the type of this field and what type of
     value this field has. It should be either ValueType_Number,
     ValueType_String, or ValueType_Photo.
    :type value_type: str
    """

    _validation = {
        'value_type': {'required': True},
    }

    _attribute_map = {
        'number_value': {'key': 'numberValue', 'type': 'float'},
        'photo_value': {'key': 'photoValue', 'type': '[DocumentFieldCreatePhotoValueItem]'},
        'string_value': {'key': 'stringValue', 'type': 'str'},
        'value_type': {'key': 'valueType', 'type': 'str'},
    }

    def __init__(self, value_type, number_value=None, photo_value=None, string_value=None):
        super(DocumentFieldCreate, self).__init__()
        self.number_value = number_value
        self.photo_value = photo_value
        self.string_value = string_value
        self.value_type = value_type
