# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .document_base import DocumentBase


class Document(DocumentBase):
    """Document.

    :param dispatch_job_id: ID of the Samsara dispatch job for which the
     document is submitted
    :type dispatch_job_id: long
    :param notes: Notes submitted with this document.
    :type notes: str
    :param document_type: Descriptive name of this type of document.
    :type document_type: str
    :param driver_created_at_ms: The time in Unix epoch milliseconds that the
     document is created.
    :type driver_created_at_ms: long
    :param driver_id: ID of the driver for whom the document is submitted
    :type driver_id: long
    :param fields: The fields associated with this document.
    :type fields: list[~swagger.models.DocumentField]
    :param vehicle_id: VehicleID of the driver at document creation.
    :type vehicle_id: long
    """

    _validation = {
        'document_type': {'required': True},
        'driver_created_at_ms': {'required': True},
        'driver_id': {'required': True},
        'fields': {'required': True},
    }

    _attribute_map = {
        'dispatch_job_id': {'key': 'dispatchJobId', 'type': 'long'},
        'notes': {'key': 'notes', 'type': 'str'},
        'document_type': {'key': 'documentType', 'type': 'str'},
        'driver_created_at_ms': {'key': 'driverCreatedAtMs', 'type': 'long'},
        'driver_id': {'key': 'driverId', 'type': 'long'},
        'fields': {'key': 'fields', 'type': '[DocumentField]'},
        'vehicle_id': {'key': 'vehicleId', 'type': 'long'},
    }

    def __init__(self, document_type, driver_created_at_ms, driver_id, fields, dispatch_job_id=None, notes=None, vehicle_id=None):
        super(Document, self).__init__(dispatch_job_id=dispatch_job_id, notes=notes)
        self.document_type = document_type
        self.driver_created_at_ms = driver_created_at_ms
        self.driver_id = driver_id
        self.fields = fields
        self.vehicle_id = vehicle_id
