# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ListOKResponse(Model):
    """ListOKResponse.

    :param vehicles:
    :type vehicles: list[~swagger.models.VehicleMaintenance]
    """

    _attribute_map = {
        'vehicles': {'key': 'vehicles', 'type': '[VehicleMaintenance]'},
    }

    def __init__(self, vehicles=None):
        super(ListOKResponse, self).__init__()
        self.vehicles = vehicles
