# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SensorHistoryResponse(Model):
    """Contains the results for a sensor history request. Each result contains a
    timestamp and datapoint for each requested (sensor, field) pair.

    :param results:
    :type results: list[~swagger.models.SensorHistoryResponseResultsItem]
    """

    _attribute_map = {
        'results': {'key': 'results', 'type': '[SensorHistoryResponseResultsItem]'},
    }

    def __init__(self, results=None):
        super(SensorHistoryResponse, self).__init__()
        self.results = results
